### ISSUE TITLE
Recompiles all sass files with every build even if unchanged

### ISSUE THREAD

**Issue by chriseppstein** [sindresorhus/gulp-ruby-sass#111]
By default, the sass `--update` command will only recompile those sass files which are newer (or have a dependency that is newer) than the output css file. However, it seems like the temp directories being used cause this to not work. Can you think of some way to preserve the optimized rebuild that sass usually performs (maybe copy the prebuilt css files to the temp output directory and set mtimes explicitly on them?), it can save a lot of time on large sass projects.

**Comment by robwierzbowski** [comment]
I see two paths to fix this.

1. Rely on Sass's caching. Upside: caching is optimized for Sass in particular. Downside: we'd need a `clear()` function to clear the results between Sass tasks or when a source file is deleted.

2. Use some sort of gulp incremental build task. Upsides: we'd have full control, no need for `clear()` function. Downsides: we'd lock people into one gulp way to build incrementally, more required options, more code and functionality to maintain.

I'm leaning towards 1. Opinions welcome.

**Comment by lagden** [comment]
@robwierzbowski I left the `Gulp`... I feel more comfortable working with `Grunt`.
But I will make a test to confirm if is ok...

**Comment by philipb3** [comment]
I like to be able to disable sass caching in my gulp-ruby-sass task. I use Sublime Text's GoTo Anything shortcut to search for files in my project and sass cache pollutes my file structure with similarly named .scss files. 

That said, for larger projects with several large files, reducing compile time with incremental builds are more important that being able disable sass caching.

**Comment by mattfelten** [comment]
If you use Sublime Text's Project feature, you can exclude the .sass-cache folder from the project.

**Comment by robwierzbowski** [comment]
Fixed, will be released in 2.0.

**Comment by robwierzbowski** [comment]
Fixed with #260.
