### ISSUE TITLE
Disabling sourcemaps and Sass 3.4

### ISSUE THREAD

**Issue by caiquecastro** [sindresorhus/gulp-ruby-sass#113]
Hi everyone, are you facing problems with Sass 3.4? its generating a map file instead of the compiled css.

**Comment by sudarshanb11** [comment]
thanks @milesj your solution helped me deal with issue, i.e., using 'sourcemap=none': true stopped printing the "map" output into my final css.
I'm using gulp and it looks something like this now.
/* inside a gulp task code */
return gulp.src(['app/styles/*'])
        .pipe($.rubySass({
            style: 'expanded',
            precision: 10,
            'sourcemap=none': true,
            loadPath: ['./bower_components']
        }))
        .pipe($.autoprefixer('last 1 version'))
        .pipe($.concat('app.css'))
        .pipe(gulp.dest('../app/assets/stylesheets/'))
        .pipe($.size());
