### ISSUE TITLE
Permissions error

### ISSUE THREAD

**Issue by mattfelten** [sindresorhus/gulp-ruby-sass#121]
So my development environment is a multi-user Linux server and I'm trying to get Gulp working for all users. It looks like when I run `gulp css` to compile, it creates a temp directory at /tmp/gulp-ruby-sass/ but for some reason only my user can run the gulp command again. Everyone else gets

```
Error: EACCES, permission denied '/tmp/gulp-ruby-sass/_14139e58-9ebe-4c0f-beca-73a65bb01ce9'
    at Object.fs.unlinkSync (fs.js:771:18)
    ...
```

It works if another user runs `sudo gulp css` but then the files are owned by root and everyone has to use sudo to do it.

Is there a way to clear the /tmp/gulp-ruby-sass/ directory after running the sass command? Or maybe set a custom directory instead of at /tmp, maybe on the user level like at ~/tmp?

**Comment by nivassri** [comment]
OptionParser::InvalidOption: invalid option: --exclude-ruby-options=includePaths 
 Use --trace for backtrace.

please give any solution for this problem

**Comment by robwierzbowski** [comment]
Please don't post the same question on multiple issues.

**Comment by lkmorlan** [comment]
Perhaps the default tmp dir should be /tmp/gulp-ruby-sass-USERNAME/
