### ISSUE TITLE
Generated files have wrong permissions

### ISSUE THREAD

**Issue by baskerville** [sindresorhus/gulp-ruby-sass#139]
After running the default task of the following `gulpfile.js`:
```
var gulp = require("gulp"),
    sass = require("gulp-ruby-sass");

gulp.task("default", function () {
	gulp.src("foo.scss")
	.pipe(sass())
	.pipe(gulp.dest("css"));
});
```
the output of `stat -f "%p %N" css/*` is:
```
100755 css/foo.css
100755 css/foo.css.map
```

**Comment by PeterDaveHello** [comment]
Should be 644 or 664 I think, because they are not executable.

**Comment by robwierzbowski** [comment]
The discussion for this continues in the closed PR https://github.com/sindresorhus/gulp-ruby-sass/pull/186/. I think this will be a no-fix, unless we find out that it's this plugin in specific (not gulp or Sass) that's changing file permissions.
