### ISSUE TITLE
Removing css attributes when it's value starts with "-"

### ISSUE THREAD

**Issue by arekbartnik** [sindresorhus/gulp-ruby-sass#140]
My only example: `display: -webkit-box;` compiles to nothing. I use this for text clamp in webkit browsers.

**Comment by v1p** [comment]
It's removing those attributes even without gulp-autoprefixer.

**Comment by robwierzbowski** [comment]
What does running Sass directly get you? What other tasks are you running?

**Comment by v1p** [comment]
@robwierzbowski : I misread @sindresorhus's comment, that sass itself is removing these values probably and "must" use auto-prefixed for this. 
For your question, I had opened & now closed this ticket https://github.com/sindresorhus/gulp-ruby-sass/issues/188

**Comment by v1p** [comment]
@robwierzbowski , @sindresorhus Could you please suggest a fix to get the https://github.com/sindresorhus/gulp-ruby-sass/issues/188 working ?
