### ISSUE TITLE
Sourcemap sources have an absolute path 1.0.0-alpha

### ISSUE THREAD

**Issue by PhilipRowe** [sindresorhus/gulp-ruby-sass#161]
I am trying out the new alpha and am struggling with the sourcemaps sources having fixed paths e.g "../../../../../../../../../../C:/xampp-1.8.2/htdocs/..............." Is it because i am using the loadpath option of sass? my complete task is below:

```javascript
gulp.task('styles', function() {
    return $.rubySass('assets/scss', {
        style: 'expanded',
        precision: 10,
        sourcemap: true,
        compass: true,
        require: ['susy'],
        loadPath: ["../location1/scss/", "../location2/scss/"]
    })
    .on('error', errorHandler)
    .pipe($.sourcemaps.write('maps', {
        includeContent: false,
        sourceRoot: '/assets/scss'
    }))
    .pipe(gulp.dest('css'))
    .pipe($.ignore.exclude('**/*.map'))
    .pipe($.rename({suffix: '.min'}))
    .pipe($.csso())
    .on('error', errorHandler)
    .pipe(gulp.dest('css'))
    .pipe($.notify({ message: 'Styles task complete', onLast: true, }));
});
```

Thanks in advance :-)

**Comment by polarathene** [comment]
I've tried that commit and pulled the latest from github with no changes for windows. I'm still getting filepaths like described in the first post. The readme also says that inline sourcemaps "just work", I've decoded the base64 in the css file and it provides this:
```JSON
{
    "version": 3,
    "mappings": "AAGA,SAAS;EAAE,MAAM,EAAE,UAAa;EAAE,KAAK,ECHhC,OAAO;;ADKd,SAAS;EACP,MAAM,EAAE,UAAa;EACrB,KAAK,ECND,IAAI;EDOR,OAAO,EERD,GAAG",
    "sources": ["../../../../C:/Development/Web/Test-Gulp/scss/main.scss","../../../../C:/Development/Web/Test-Gulp/scss/_config.scss","../../../../C:/Development/Web/Test-Gulp/scss/test/_num.scss"],
    "names": [],
    "file": "main.css",
    "sourceRoot": "/source/",
    "sourcesContent": []
}
```

It's not embedding any sourcesContent? I can make external maps work by manually editing the file paths.
```Javascript
gulp.task('grsass', function(){
    var scss_filename = 'scss/';
    rsass(scss_filename, {sourcemap:true, noCache:true})
        .pipe(sourcemaps.write())
        .pipe(gulp.dest('./build/css/'));
});
```

I'm fine with external source content, the incorrect file path is the main problem though as I can't pass that sourcemap onto autoprefixer unless I correct the file paths prior.

**Comment by PhilipRowe** [comment]
@robwierzbowski 
Base path: C:\xampp-1.8.2\htdocs\sites\test\assets\scss
Absolute path: /C:/xampp-1.8.2/htdocs/sites/test/assets/scss/test.scss

Im not sure if Windows treats C: as an absolute path how would i check?

**Comment by UltCombo** [comment]
Paths starting with drive letter followed by `:` are absolute, yes.

**Comment by robwierzbowski** [comment]
Thanks for all the info everyone. Going to try and fix this one up now.

**Comment by robwierzbowski** [comment]
Tests added for decoding path bug.

**Comment by robwierzbowski** [comment]
@PhilipRowe and @polarathene, can you try installing and running the `rw/1.0-windows-debug` branch on a single file? It will log sourcemapSource, base, and absoluteSourcePath; can you post the results here?

On OSX/Unix we want that extra slash for absolute file paths. On windows we might not need it. Possible fix could be to remove all three slashes then convert the path to absolute with a function that is aware of how to do this correctly dependent on OS.

**Comment by robwierzbowski** [comment]
Added a possible fix in that branch too. Not sure if it's robust; logging will give us a better idea.

**Comment by PhilipRowe** [comment]
@robwierzbowski  Here is whats logged when on the latest rw/1.0-windows-debug
sourcemapSource: file:///C:/xampp-1.8.2/htdocs/sites/sasstest/scss/main.scss
base: C:\xampp-1.8.2\htdocs\sites\sasstest\scss
absoluteSourcePath: C:/xampp-1.8.2/htdocs/sites/sasstest/scss/main.scss
absoluteSourcePath resolved: C:\xampp-1.8.2\htdocs\sites\sasstest\scss\main.scss

I compiled the project and the sourcemaps maps file appeared to have the correct path.

**Comment by robwierzbowski** [comment]
Awww yissss. Ok, with that I should be able to neaten things up and get the
paths working for Windows and OSX/Unix. Will ping with a final commit for
you to test and release a new alpha (maybe even just 1.0, think this is one
of the last remaining serious issues).

On Monday, January 19, 2015, PhilipRowe <notifications@github.com> wrote:

> @robwierzbowski <https://github.com/robwierzbowski> Here is whats logged
> when on the latest rw/1.0-windows-debug
> sourcemapSource:
> file:///C:/xampp-1.8.2/htdocs/sites/sasstest/scss/main.scss
> base: C:\xampp-1.8.2\htdocs\sites\sasstest\scss
> absoluteSourcePath: C:/xampp-1.8.2/htdocs/sites/sasstest/scss/main.scss
> absoluteSourcePath resolved:
> C:\xampp-1.8.2\htdocs\sites\sasstest\scss\main.scss
>
> I compiled the project and the sourcemaps maps file appeared to have the
> correct path.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sindresorhus/gulp-ruby-sass/issues/161#issuecomment-70463548>
> .
>


-- 
Rob Wierzbowski
@robwierzbowski <http://twitter.com/#!/robwierzbowski>
http://github.com/robwierzbowski
http://robwierzbowski.com

**Comment by robwierzbowski** [comment]
OK, can anyone who's had this issue try installing version 1.0.0-alpha.2 and see if it fixes the issue?

**Comment by polarathene** [comment]
@robwierzbowski I've just tested the branch and can confirm it outputs filepaths in sourcemaps correctly now.

Visualization of mapping [here](http://sokra.github.io/source-map-visualization/#base64,Lml0ZW1fb25lIHsNCiAgZmlsdGVyOiBzZXBpYSgwLjUpOw0KICBjb2xvcjogIzNiYmZjZTsgfQ0KDQouaXRlbV90d28gew0KICBmaWx0ZXI6IHNlcGlhKDAuNSk7DQogIGNvbG9yOiAjYTIyOw0KICBvcGFjaXR5OiAwLjU7IH0NCg0KDQoKLyojIHNvdXJjZU1hcHBpbmdVUkw9bWFpbi5jc3MubWFwICov,eyJ2ZXJzaW9uIjozLCJtYXBwaW5ncyI6IkFBR0EsU0FBUztFQUFFLE1BQU0sRUFBRSxVQUFhO0VBQUUsS0FBSyxFQ0hoQyxPQUFPOztBREtkLFNBQVM7RUFDUCxNQUFNLEVBQUUsVUFBYTtFQUNyQixLQUFLLEVDTkQsSUFBSTtFRE9SLE9BQU8sRUVSRCxHQUFHIiwic291cmNlcyI6WyJtYWluLnNjc3MiLCJfY29uZmlnLnNjc3MiLCJ0ZXN0L19udW0uc2NzcyJdLCJuYW1lcyI6W10sImZpbGUiOiJtYWluLmNzcyIsInNvdXJjZVJvb3QiOiIuLi8uLi9zY3NzLyJ9,QGltcG9ydCAiY29uZmlnIjsNCkBpbXBvcnQgInRlc3QvbnVtIjsNCg0KLml0ZW1fb25leyBmaWx0ZXI6IHNlcGlhKCR2YWx1ZSk7IGNvbG9yOiRibHVlOyB9DQoNCi5pdGVtX3R3b3sNCiAgZmlsdGVyOiBzZXBpYSgkdmFsdWUpOw0KICBjb2xvcjogJHJlZDsNCiAgb3BhY2l0eTogJHZhbHVlOw0KfQ==,JGJsdWU6ICMzYmJmY2U7DQokcmVkOiAjYTIyOw==,JHZhbHVlOiAwLjU7)

Sourcemap output:
```JSON
{
    "version": 3,
    "mappings": "AAGA,SAAS;EAAE,MAAM,EAAE,UAAa;EAAE,KAAK,ECHhC,OAAO;;ADKd,SAAS;EACP,MAAM,EAAE,UAAa;EACrB,KAAK,ECND,IAAI;EDOR,OAAO,EERD,GAAG",
    "sources": [
        "main.scss",
        "_config.scss",
        "test/_num.scss"
    ],
    "names": [],
    "file": "main.css",
    "sourceRoot": "../../scss/"
}
```

Gulp Task:
```Javascript
gulp.task('rsass', function(){
    var scss_filename = 'scss/';
    return rsass(scss_filename, {sourcemap:true, noCache:true})
        .pipe(sourcemaps.write('.',{includeContent:false, sourceRoot:'../../scss/'}))
        .pipe(gulp.dest('./build/css/'));
});
```

**Comment by robwierzbowski** [comment]
Thanks! Marking as fixed.
