### ISSUE TITLE
stderr: Errno::EACCES: Permission denied

### ISSUE THREAD

**Issue by donum** [sindresorhus/gulp-ruby-sass#174]
When executing the following gulp task:

```javascript
gulp.task('assets-css',function(){
	return sass('lib/scripts/js/vendor/slick/1.3.15',{
			container: 'gulp-ruby-sass-assets-css-slick',
			sourcemap: false,
			noCache: true,
			style: "compressed"
		})
		.pipe(autoprefixer())
		.pipe(gulp.dest('lib/scripts/js/vendor/slick/1.3.15'));
});
```

I get the following error message:
> gulp-ruby-sass stderr: Errno::EACCES: Permission denied - lib/scripts/js/vendor/slick/1.3.15

When I rename the folder "1.3.5" to "test" the error message is gone.

Seems like something goes wrong when there are dots in the foldername.

Environment details:
- Windows 7 64bit
- Ruby 1.9.3p551
- nodejs 0.10.22
- gulp 3.8.10
- gulp-ruby-sass 1.0.0-alpha

Wonder where this issue exactly comes from.

Thanks

**Comment by robwierzbowski** [comment]
Can you give me the output when running `gulp assets-css --verbose`, and also double check that the directory `lib/scripts/js/vendor/slick/1.3.15` exists, and if it works if you specify a different `gulp.dest`?

**Comment by donum** [comment]
I will only be able to answer on monday.

**Comment by robwierzbowski** [comment]
No worries. Thanks.

On Friday, January 16, 2015, Daniel Schmidt <notifications@github.com>
wrote:

> I will only be able to answer on monday.
>
> > Am 16.01.2015 um 20:12 schrieb Rob Wierzbowski <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>>:
> >
> > Can you give me the output when running gulp assets-css --verbose, and
> also double check that the directory lib/scripts/js/vendor/slick/1.3.15
> exists, and if it works if you specify a different gulp.dest?
> >
> > —
> > Reply to this email directly or view it on GitHub.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sindresorhus/gulp-ruby-sass/issues/174#issuecomment-70343557>
> .
>


-- 
Rob Wierzbowski
@robwierzbowski <http://twitter.com/#!/robwierzbowski>
http://github.com/robwierzbowski
http://robwierzbowski.com

**Comment by robwierzbowski** [comment]
Closing. If you're still experiencing issues please re-open.

**Comment by pyrsmk** [comment]
I'm having the same problem really often. I'm using no option to compile my files : 

```js
sass(paths[name], {loadPath: ['.']})
	.pipe( plumber() )
	.pipe( $if(prod, csso()) )
	.pipe( gulp.dest('./css/'+name) )
	.pipe( size({gzip:true}) )
```

**Comment by robwierzbowski** [comment]
If you remove plumber and use the built in error logger (see documentation
examples) does the error continue?

On Tuesday, November 10, 2015, Aurélien Delogu <notifications@github.com>
wrote:

> I'm having the same problem really often. I'm using no option to compile
> my files :
>
> sass(paths[name], {loadPath: ['.']})
>     .pipe( plumber() )
>     .pipe( $if(prod, csso()) )
>     .pipe( gulp.dest('./css/'+name) )
>     .pipe( size({gzip:true}) )
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sindresorhus/gulp-ruby-sass/issues/174#issuecomment-155394747>
> .
>


-- 
Rob Wierzbowski
@robwierzbowski <http://twitter.com/#!/robwierzbowski>
http://github.com/robwierzbowski
http://robwierzbowski.com

**Comment by pyrsmk** [comment]
Yep

**Comment by pyrsmk** [comment]
Ok, no, sorry, I still have the issue ^^
