### ISSUE TITLE
Sourcemap not working like documented

### ISSUE THREAD

**Issue by TheDutchCoder** [sindresorhus/gulp-ruby-sass#176]
Hey there,

I'm struggling a lot with the way this plugin handles sourcemaps, mainly because the documented options throw errors.

Here's my gulp task:
```js
// SASS
gulp.task('css:sass', function() {

    return gulp.src('sass/**/*.scss')
        .pipe(plugins.rubySass({ style: 'compressed', sourcemap: true, sourcemapPath: 'sass' }))
        .pipe(gulp.dest('./'))
        .pipe(plugins.livereload());

});
```

A couple of things:

  1. `sourcemap: true` throws an error (deprecation warning: passing --soucemap without a value is deprecated), obviously it's not without a value.
  2. According to the docs, I should actually pass in a string, but when I do that, the fabove error still shows, but also the following: 'Error: error No such file or directory @ rb_sysopen - inline'.

The only way I can get this to work is with the first example, eventhough it keeps throwing deprecation warnings (which I'd rather not have).

My sass files are in `/sass/` and the compiled css is in the root, so I need to add the `/sass/` directory for the sourcemap.

Any help would be appreciated.

**Comment by robwierzbowski** [comment]
Closing as a misunderstanding with 1.0. Will ping when globbing is added.
