### ISSUE TITLE
Extra sass dir getting created

### ISSUE THREAD

**Issue by rightaway** [sindresorhus/gulp-ruby-sass#177]
My Gulpfile.js is

```
var gulp = require('gulp');
var sass = require('gulp-ruby-sass');

gulp.task('sass', function() {
    gulp.src('proj/file/sass/*.scss')
        .pipe(sass({noCache: true, require: ['susy']}))
        .pipe(gulp.dest('proj/file/css'))
});

gulp.task('watch', function() {
    gulp.watch('proj/file/sass/*.scss', ['sass']);
});

gulp.task('default', ['sass', 'watch']);
```

Everytime I make a change to proj/static/sass/test.css, an empty directory gets created in proj/file/css/ called 'sass', why is this? (The test.css and test.css.map get correctly created in proj/file/css.) If I delete that empty sass directory it gets recreated. I think it's being indicated by the output

```
[23:53:04] gulp-ruby-sass: directory
[23:53:04] gulp-ruby-sass: write test.css
      write test.css.map
```

How can I avoid the unnecessary directory getting created? I'm new to this so I might just not know how to configure this properly.

**Comment by polarathene** [comment]
I experienced this once, I think it was when I had my src target defined for the alpha preview (just a folder no * or extension), and I rolled back to the current release using the same variable for src target instead of my previous one eg `proj/file/sass/main.scss`. Perhaps try compiling a single .scss instead of `*.scss`.

**Comment by robwierzbowski** [comment]
Please try the alpha release. Leaving this open, but I won't be looking into bug reports for the 0.7.x releases right now.

**Comment by rightaway** [comment]
Seems to be fine now, I think it's as @polarathene described.
