### ISSUE TITLE
Issue when setting sourcemapPath to .

### ISSUE THREAD

**Issue by ryanburnette** [sindresorhus/gulp-ruby-sass#180]
I'm using alpha@1.0.0 and Sass 3.4.9.

I have my sourcemap settings as follows:

```javascript
var options = {
  sourcemap: true
, sourcemapPath: '.'
}
```

I get the following output from gulp-ruby-sass though:

```
[16:26:26] gulp-ruby-sass stderr: OptionParser::InvalidOption: invalid option: --sourcemap-path=.
  Use --trace for backtrace.
```

This might be related to what's being discussed in #161.

**Comment by polarathene** [comment]
You no longer use sourcemapPath, instead use gulp-sourcemaps and it's settings.
```Javascript
var gulp = require('gulp');
var rsass = require('gulp-ruby-sass');
var sourcemaps = require('gulp-sourcemaps');

gulp.task('rsass', function(){
    var scss_filename = 'scss/';
    rsass(scss_filename, {sourcemap:true})
        .on('error',function(err){console.log(err.message);})
        .pipe(sourcemaps.write('.',{includeContent:false, sourceRoot:'../../scss/'}))
        .pipe(gulp.dest('./build/css/'))
})
```

`sourceContents` doesn't appear to be populated even if you tell it to, if you are a Windows user at least in my case the file path for your `sources` is invalid, you'll need to manually correct it which prevents you from another task that would use the sourcemap such as autoprefixer or minify.

**Comment by robwierzbowski** [comment]
Thanks @polarathene!
