### ISSUE TITLE
Multiple Streams running

### ISSUE THREAD

**Issue by chapinkapa** [sindresorhus/gulp-ruby-sass#181]
We should throw an error when multiple streams of gulp-ruby-sass are running. Something like 'Multiple instances of ruby-sass are running. Recommend you use containers.'

**Comment by sindresorhus** [comment]
Why?

**Comment by UltCombo** [comment]
It *could* be useful to warn the user in case they forget to provide the container option, but in the end it boils down to a rtfm issue.

**Comment by robwierzbowski** [comment]
Pull requests accepted once 1.0 is released. I think this could be a nice to have if it doesn't add code complexity, but in essence it's fixed by reading the manual.
