### ISSUE TITLE
What about images? image-url() doesn't work

### ISSUE THREAD

**Issue by OnkelTem** [sindresorhus/gulp-ruby-sass#182]
I couldn't get coherent results with generating css with gulp-ruby-sass: images-url() always resolves to wrong paths.

The reason is that gulp-ruby-sass writes css files to /tmp/gulp-ruby-sass dir, **where 'images' dir doesn't exist**, and this makes compass to generate incorrect paths to images.

Supposing this structure:

```
myproject/
  config.rb
  src/
    images/
    sass/
  www/
    build/
      images/
      css/
```

This minimal config.rb perfectly works when launching it with `compass`:

```
http_path = '/'
css_path = 'www/build/css'
images_path = 'www/build/images'
relative_assets = true
```

example path: `url(../images/1.png)`

But when using gulp-ruby-sass it looks like `url('../../var/www/sites/myproject/www/build/images/ctrl-close.png')`

**Comment by rasco** [comment]
I also have a setup where all my source files are in a directory `src` and the stylesheets and images are in `src/stylesheets` and `src/images`.
But my `gulpfile.js` is not in `src`; therefore, compass tries to find the images in `images`, instead of`'src/images`, which fails.
A temporary workaround that worked for me was changing the gulp working directory using `process.chdir('./src')`;

**Comment by tonnyfdrs** [comment]
Good day, have same problem, do you make any solution's ?

**Comment by blackjackcf** [comment]
I'm having the same issue with asset-data-url and asset-url.

**Comment by tonnyfdrs** [comment]
('gulp-compass') my design

**Comment by robwierzbowski** [comment]
Does anyone wants to try with the latest 2.0 version and report back? I may tackle Compass integration next, although I don't use it and I get the feeling it's being used less and less lately.

**Comment by robwierzbowski** [comment]
By which I mean it's not at the top of my priority list, but I'd still like to support.

**Comment by OnkelTem** [comment]
Sorry for I can't provide any assistance as I've migrated to libsass. Speed over functionaly.

**Comment by robwierzbowski** [comment]
:+1:

**Comment by stevemao** [comment]
Is there any reason why not using [gulp-compass](https://github.com/appleboy/gulp-compass)?

**Comment by sindresorhus** [comment]
Hey, sorry, this project is now deprecated because Ruby Sass is deprecated.

See: https://github.com/sindresorhus/gulp-ruby-sass#deprecated
