### ISSUE TITLE
style.css compiles inside /sass folder no matter which path is set

### ISSUE THREAD

**Issue by vedranjaic** [sindresorhus/gulp-ruby-sass#183]
Hello, sorry if this was asked before, but I'm not finding anything about it.
No matter what path I set in my gulpfile, style.css gets compiled inside sass folder.
Problem persists using either gulp-sass or gulp-ruby-sass

Ex,
`.pipe(gulp.dest('.'))`
compiles in `project/sass/style.css` instead of `project/style.css`

`.pipe(gulp.dest('/css'))`
compiles in `project/css/sass/style.css` instead of `project/css/style.css`

etc...
Does anyone know how to fix this?

**Comment by robwierzbowski** [comment]
Can you post your whole task?

On Friday, January 2, 2015, Vedran Jaic <notifications@github.com> wrote:

> Hello, sorry if this was asked before, but I'm not finding anything about
> it.
> No matter what path I set in my gulpfile, style.css gets compiled inside
> sass folder.
> Problem persists using either gulp-sass or gulp-ruby-sass
>
> Ex,
> .pipe(gulp.dest('.'))
> compiles in project/sass/style.css instead of project/style.css
>
> .pipe(gulp.dest('/css'))
> compiles in project/css/sass/style.css instead of project/css/style.css
>
> etc...
> Does anyone know how to fix this?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sindresorhus/gulp-ruby-sass/issues/183>.
>


-- 
Rob Wierzbowski
@robwierzbowski <http://twitter.com/#!/robwierzbowski>
http://github.com/robwierzbowski
http://robwierzbowski.com

**Comment by vedranjaic** [comment]
Hi Rob, sure, here it is...
I was running this on my laptop, and funny thing is that if I run a fresh install of node/gulp/etc... on another mac, it compiles as it should...
I did a clean install of the OS on my laptop yesterday (I had to anyway, not because of this error :)), and with new install of node/gulp/etc... the problem still persisted...

In this case I am using gulp-sass, in case when I tried with gulp-ruby-sass I used only `style: 'expanded'`to match the syntax, but problem is there even in case of clean `.pipe(sass())` 

<pre>
// Gulp & plugins
var gulp = require('gulp'),
	gutil = require('gulp-util'),
	sass = require('gulp-sass'),
	autoprefixer = require ('gulp-autoprefixer'),
	uglify = require('gulp-uglify'),
	imagemin = require('gulp-imagemin'),
	pngquant = require('imagemin-pngquant'),
	browserSync = require('browser-sync'),
	reload = browserSync.reload,
	notify = require("gulp-notify");

// Sources
var src = {
	images: 'app/src/images/*',
	sass: 'app/src/**/*.scss',
	php: 'app/**/*.php',
	js: 'app/src/js/**/*.js'
}

// Destinations
var dest = {
	images: 'app/dest/images',
	css: 'app/',
	js: 'app/dest/js'
}



// TASKS
// Minify js
gulp.task('scripts', function() {

	return gulp.src(src.js)
		.pipe(uglify())
		.on("error", notify.onError({
			title: "Uglify JS error",
			message: "<%= error.message %>"
		}))
		.pipe(gulp.dest(dest.js))

});

// Compile SASS
gulp.task('styles', function () {

	return gulp.src(src.sass)
		.pipe(sass({
			style: 'expanded',
			errLogToConsole: false,
			require: ['susy'],
			onError: function(err) {
				return notify().write(err);
			}
		}))
		.pipe(gulp.dest(dest.css))
		.pipe(reload({
			stream:true
		}))
		.pipe(notify('SASS approves this syntax!'));

});

// Compile SASS.min
gulp.task('styles-min', function () {

	return gulp.src(src.sass)
		.pipe(sass({
			style: 'compressed',
			errLogToConsole: false,
			onError: function(err) {
				return notify().write(err);
			}
		}))
		.pipe(autoprefixer())
		.pipe(gulp.dest(dest.css))

});

// Optimize images
gulp.task('images', function () {
	return gulp.src(src.images)
		.pipe(imagemin({
			progressive: true,
			svgoPlugins: [{
				removeViewBox: false,
				cleanupIDs: false,
				cleanupAttrs: false
			}],
			use: [pngquant()],
			onError: function(err) {
				return notify().write(err);
			}
		}))
		.pipe(gulp.dest(dest.images))
});

// Browser-sync
gulp.task('browser-sync', function() {
	browserSync({
		proxy: "localhost:8888",
		ghostMode: false,
		notify: false,
		open: "external"
	});
	gulp.watch(src.php, reload);
	gulp.watch(['style.css'], reload);
	gulp.watch(dest.images, reload);
	gulp.watch(src.js, reload);
});

// Watch
gulp.task('watch', function() {
	gulp.watch(src.sass, ['styles']);
})

// Default
gulp.task('default', ['scripts', 'styles', 'browser-sync'], function(){
	gulp.watch(src.sass, ['styles']);
	gulp.watch(src.js, ['scripts']);
});

// Production
gulp.task('production', ['scripts', 'styles-min', 'images']);
</pre>

**Comment by vedranjaic** [comment]
Wow, I don't believe it was this stupid, I re-typed the styles task and it works
If I copy/paste the same snippet of code, it doesn't work...

**Comment by robwierzbowski** [comment]
Sounds like there's a little error in your syntax somewhere but you've fixed it. Looks like you're using gulp-ruby-sass 0.7.x too, so closing this since I'm concentrating on the 1.0 release. I'd say the fix for now is to use your re-typed task :).
