### ISSUE TITLE
sourcemap can't disable

### ISSUE THREAD

**Issue by flftfqwxf** [sindresorhus/gulp-ruby-sass#184]
sourcemap set false,but sourcemap files is generated

add some codes:

after lines 145:
  if (!options.sourcemap) {
            args.push('--sourcemap=none');

        }

**Comment by robwierzbowski** [comment]
Fixed in 1.0 alpha and on master. See 1.0 pull request.

**Comment by flftfqwxf** [comment]
@robwierzbowski  
Thanks!
