### ISSUE TITLE
How to specify order of files?

### ISSUE THREAD

**Issue by rightaway** [sindresorhus/gulp-ruby-sass#189]
1.0.0-alpha doesn't support globs, doesn't seem to support an array of files either. Only a single source directory. How can I specify the order I want the .scss files use, particularly if I want to concat them first?

**Comment by robwierzbowski** [comment]
One way would be to make your files partials and import them into a single file that you then process (which is how you would do it with Sass). Or, you could use a concat plugin first, write to disk, and then process the resulting Sass file. 

Globs will be supported after the release of 1.0. Currently I'm fixing sourcemap and path bugs to get the basic version out.

**Comment by rightaway** [comment]
When globs are supported does that mean passing in an array of paths will also be supported? Like

```
var files = [
  'onefile',
  'anotherfile'
]
```

**Comment by robwierzbowski** [comment]
It will work just like `gulp.src` works in relation to globs. You might want to double check, I'm not sure if passing an array means the files are processed in that order. Gulp doesn't really like order dependent processing — it would rather do it all at once.

**Comment by robwierzbowski** [comment]
Looked a little closer at the Sass docs: your only options for compiling Sass files are to specify a single source and result file or a source directory and result directory. For the near future that will be your only options with this plugin as well.
