### ISSUE TITLE
TypeError: Arguments to path.join must be strings

### ISSUE THREAD

**Issue by matthewjewell** [sindresorhus/gulp-ruby-sass#191]
Hi,

For the sake of this example, assume my code is [identical to this](http://ericlbarnes.com/setting-gulp-bower-bootstrap-sass-fontawesome/), and my configuration an untouched instance of Laravel's homestead (Windows).

The following error is returned after running `gulp watch` and then making a change to a scss file.

```
[19:36:34] TypeError: Arguments to path.join must be strings
    at path.js:360:15
    at Array.filter (native)
    at Object.exports.join (path.js:358:36)
    at module.exports (/home/vagrant/projects/ttv-laravel/node_modules/gulp-ruby-sass/index.js:61:15)
    at Gulp.<anonymous> (/home/vagrant/projects/ttv-laravel/Gulpfile.js:24:15)
    at module.exports (/home/vagrant/projects/ttv-laravel/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:34:7)
    at Gulp.Orchestrator._runTask (/home/vagrant/projects/ttv-laravel/node_modules/gulp/node_modules/orchestrator/index.js:273:3)
    at Gulp.Orchestrator._runStep (/home/vagrant/projects/ttv-laravel/node_modules/gulp/node_modules/orchestrator/index.js:214:10)
    at Gulp.Orchestrator.start (/home/vagrant/projects/ttv-laravel/node_modules/gulp/node_modules/orchestrator/index.js:134:8)
    at Gulp.<anonymous> (/home/vagrant/projects/ttv-laravel/node_modules/gulp/index.js:36:18)
```

Collated code from the link above (what I am trying):

```js
var gulp = require('gulp'),    
    sass = require('gulp-ruby-sass')
    autoprefix = require('gulp-autoprefixer')
    notify = require("gulp-notify")
    bower = require('gulp-bower');

var config = {
    sassPath: './app/assets/sass',
    bowerDir: './bower_components'
}

gulp.task('bower', function() {
    return bower()
        .pipe(gulp.dest(config.bowerDir))
});

gulp.task('icons', function() {
    return gulp.src(config.bowerDir + '/fontawesome/fonts/**.*')
        .pipe(gulp.dest('./public/fonts'));
});

gulp.task('css', function() {
    return gulp.src(config.sassPath + '/main.scss')
        .pipe(sass({
            style: 'compressed',
            loadPath: [
                './app/assets/sass',
                config.bowerDir + '/bootstrap-sass-official/assets/stylesheets',
                config.bowerDir + '/fontawesome/scss'
            ]
        })
            .on("error", notify.onError(function (error) {
                return "Error: " + error.message;
            })))
        .pipe(autoprefix('last 2 version'))
        .pipe(gulp.dest('./public/css'));
});

gulp.task('watch', function() {
    gulp.watch(config.sassPath + '/**/*.scss', ['css']);
});

gulp.task('default', ['bower', 'icons', 'css']);
```

I can't seem to get to the bottom of this one, to the point where I wonder if there is a bug to be found.

**Comment by TakenPilot** [comment]
+1, I'm getting the same error.

**Comment by robwierzbowski** [comment]
What version are you using?

**Comment by matthewjewell** [comment]
`"gulp-ruby-sass": "^1.0.0-alpha.2",`

**Comment by robwierzbowski** [comment]
Check the readme -- 1.0.0 replaces gulp.src.

On Saturday, January 24, 2015, matthewjewell <notifications@github.com>
wrote:

> "gulp-ruby-sass": "^1.0.0-alpha.2",
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sindresorhus/gulp-ruby-sass/issues/191#issuecomment-71336078>
> .
>


-- 
Rob Wierzbowski
@robwierzbowski <http://twitter.com/#!/robwierzbowski>
http://github.com/robwierzbowski
http://robwierzbowski.com

**Comment by matthewjewell** [comment]
So it does. Thanks for that, closing issue.

**Comment by TakenPilot** [comment]
Sorry, I don't understand and had the same issue.  It... replaces gulp.src?

**Comment by robwierzbowski** [comment]
Docs on how to set up 1.0 are in the readme inside of the bode package or
linked at the top of the readme on this repo.

On Saturday, January 24, 2015, Dane Stuckel <notifications@github.com>
wrote:

> Sorry, I don't understand and had the same issue. It... replaces gulp.src?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sindresorhus/gulp-ruby-sass/issues/191#issuecomment-71341759>
> .
>


-- 
Rob Wierzbowski
@robwierzbowski <http://twitter.com/#!/robwierzbowski>
http://github.com/robwierzbowski
http://robwierzbowski.com

**Comment by TakenPilot** [comment]
Ah, I see, gulp.src really was removed.  Neat.  Thanks!

**Comment by fricks** [comment]
Im still getting this error :-1:

**Comment by robwierzbowski** [comment]
@fricks What is your gulp task?

**Comment by fricks** [comment]
@robwierzbowski check it...maybe im wrong

gulp.task('css', function() {
  //return gulp.src(config.sassPath + '/style.scss')
  return sass(config.sassPath + '/style.scss')
  .pipe(sass({
    style: 'normal', //normal, compressed
    loadPath: [
    './resources/sass',
    config.bowerDir + '/bootstrap-sass-official/assets/stylesheets',
    config.bowerDir + '/fontawesome/scss',
    config.bowerDir + '/Hover/scss',
    ]
  })
  .on("error", notify.onError(function (error) {
    return "Error: " + error.message;
  })))
  //.pipe(autoprefix('last 2 version'))
  .pipe(gulp.dest('./assets/css'));
});

**Comment by fricks** [comment]
Yes, I was wrong @robwierzbowski 
Here is a correct task but I still have a issue with gulp-notify. 
The error only print in iTerm.
```html
gulp.task('sass', function () {
  return sass(config.sassPath + '/style.scss', { style: 'expanded', loadPath:['./resources/sass', config.bowerDir + '/bootstrap-sass-official/assets/stylesheets', config.bowerDir + '/fontawesome/scss', config.bowerDir + '/Hover/scss', ] })
    .on('error', notify.onError(function (error){
      return "Error: " + error.message;
    }))
    .pipe(gulp.dest('./assets/css'));
});
```

**Comment by robwierzbowski** [comment]
Yeah I'm looking into the error issues. Will be fixed ASAP.

Rob Wierzbowski
@robwierzbowski <http://twitter.com/#!/robwierzbowski>
http://github.com/robwierzbowski
http://robwierzbowski.com

On Tue, Feb 10, 2015 at 7:13 PM, Joao Paulo Fricks <notifications@github.com

**Comment by fricks** [comment]
@robwierzbowski Thanks :+1:

**Comment by rendler-denis** [comment]
hey , guys! I'm trying to follow the exact same tutorial as the initial reporter and still get the error. I've read the entire issue several times and I still cannot seem to get past this issue. any help is appreciated. thanks.

**Comment by rendler-denis** [comment]
Finally tracked down a solution. For anyone else having this issue http://foundation.zurb.com/forum/posts/22280-app-typeerror-arguments-to-pathjoin-must-be-strings . Check the first comments.
