### ISSUE TITLE
Invalid option: --sourcemap=none

### ISSUE THREAD

**Issue by lifeisfoo** [sindresorhus/gulp-ruby-sass#192]
In sass < 3.4 this option doesn't exist.
```
gulp-ruby-sass stderr: /Library/Ruby/Gems/2.0.0/gems/sass-3.2.14/lib/sass/exec.rb:39:in `parse': invalid option: --sourcemap=none (OptionParser::InvalidOption)
	from /Library/Ruby/Gems/2.0.0/gems/sass-3.2.14/lib/sass/exec.rb:21:in `parse!'
	from /Library/Ruby/Gems/2.0.0/gems/sass-3.2.14/bin/sass:13:in `<top (required)>'
	from /usr/bin/sass:23:in `load'
	from /usr/bin/sass:23:in `<main>'
```

The error occur using gulp-ruby-sass 1.0.0-alpha.2 with default options
```
gulp.task('sass', function() {
  return sass('scss/main.scss')
    .pipe(gulp.dest('css'))
    .pipe(reload({ stream:true }));
});
```

**Comment by A-Zak** [comment]
God smacked, just had the same exact error and wanted to report myself.... :)

**Comment by UltCombo** [comment]
grs 1.0+ only supports Sass 3.4+ IIRC.

**Comment by lifeisfoo** [comment]
An easy workaround is to use Bundler to install a newer version of the sass gem, without overriding system defaults.

First install bundler using `sudo gem install bundler`.

Then create a  `Gemfile` inside the project with the sass dependency:
```
source 'https://rubygems.org'
gem 'sass', '>=3.4'
```

Finally install the updated sass with `bundle install` and configure gulp to use bundler version of sass with the **bundleExec** options:
```
gulp.task('sass', function() {
  return sass('scss/main.scss', {
        bundleExec: true
    })
    .pipe(gulp.dest(cssDir));
});
```

Now everything should work fine. I hope that this procedure will be documented since not every *gulpist* is a _rubyist_.

**Comment by robwierzbowski** [comment]
Thank you @lifeisfoo. 

We're probably only going to support the newest versions of Sass now and in the future. The plugin is pretty complex without backwards compatibility.
