### ISSUE TITLE
stderr: Errno::ENOENT: No such file or directory

### ISSUE THREAD

**Issue by vedranjaic** [sindresorhus/gulp-ruby-sass#194]
Hi, I started getting this error while updating to 1.0.0.alpha2 if i set to look in any folder for any .scss file:
<pre>var src = {
	sass: 'app/src/**/*.scss',
}</pre>
Only if I specifically set the path to the main style.scss file
<pre>var src = {
	sass: 'app/src/sass/style.scss',
}</pre>
everything works fine, except I have to switch to style.scss file and save it every time in order to watch the changes in sass files...

**Comment by robwierzbowski** [comment]
Link to the current docs on the home page here: https://github.com/sindresorhus/gulp-ruby-sass#note-pre-10-versions-are-no-longer-supportedplease-try-100-alpha

Important notes in the current docs here: https://github.com/sindresorhus/gulp-ruby-sass/tree/rw/1.0#important

> gulp-ruby-sass doesn't support globs yet, only single files or directories. Just like Sass.

I'm working on it, but as Sass doesn't have globs we need to do extra work to make gulp-ruby-sass support globs. 1.0 is going out as soon as I check some error handling; 1.1 will probably support globs.

The main workaround now is to compile a directory, like you would with Sass.

**Comment by donaldallen** [comment]
:+1: Definitely need this back for 1.1.

**Comment by fricks** [comment]
@donaldallen I agree! :+1:

**Comment by donaldallen** [comment]
Just to explain my use case. I have a /source folder for my site that contains all my .scss files for the main site. However, I have some special feature pages that require their own stylesheets that are in their own seperate directories. So I was using something like this in my gulpfile.js:
```javascript
return gulp.src('../features/**/source/scss/*.scss')
```
Was a huge time saver. Maybe there's a better way of doing it prior to the 1.1 release, but right now I've basically defined tasks for each feature on the site. Ugly, but it works.

**Comment by vedranjaic** [comment]
I managed to "trick" mine into compiling with a directory, but set the watch on .../** /*.scss
<pre>
// Sources
var src = {
	sass: 'src/sass/',
	scss: 'src/sass/**/*.scss',
}

// Compile SASS
gulp.task('styles', function () {
	return sass(src.sass)
		.pipe(gulp.dest(dest.css))
});

// Default
gulp.task('default', ['styles', 'browser-sync'], function(){
	gulp.watch(src.scss, ['styles']);
});
</pre>
