### ISSUE TITLE
gulp-ruby-sass stderr:...needless argument: --sourcemap=none (OptionParser::NeedlessArgument)

### ISSUE THREAD

**Issue by AlasdairSwan** [sindresorhus/gulp-ruby-sass#196]
Hi,

I am seeing an issue that appears to be the same as #145 with version 1.0.0-alpha.3. The error is:

**gulp-ruby-sass stderr: /Library/Ruby/Gems/2.0.0/gems/sass-3.3.8/lib/sass/exec.rb:41:in `parse': needless argument: --sourcemap=none (OptionParser::NeedlessArgument)**

My gulpfile function is
```javascript
gulp.task( 'css', function() {
    return sass('sass/*.scss', {
            loadPath: require('node-bourbon').includePaths,
            lineNumbers: true,
            verbose: true,
            trace: true
        })
        .pipe( gulp.dest( 'css' ) );
});
```

Any ideas how to resolve this issue? No CSS is being output. It is only since updating my version of gulp-ruby-sass and updating to move away from the gulp.src syntax that I have had an issue.

**Comment by robwierzbowski** [comment]
Lots of people have been tripped up by this. The answers you seek are in the README, also in closed issues.

**Comment by AlasdairSwan** [comment]
Hi @robwierzbowski, could you please point me in the direction of the README you mention? This file appear to be for versions before 1.0.0 https://github.com/sindresorhus/gulp-ruby-sass/blob/master/readme.md

**Comment by robwierzbowski** [comment]
Sure. In the https://github.com/sindresorhus/gulp-ruby-sass/blob/master/readme.md#note-pre-10-versions-are-no-longer-supportedplease-try-100-alpha section there's a link that says "New documentation here". In it you will find that grs supports Sass 3.4+ only, and that it currently doesn't support globs. Hope that helps — if you still have trouble feel free to post back.

**Comment by AlasdairSwan** [comment]
Thanks @robwierzbowski  Apologies, I misread my Sass version and thought it was greater than 3.4.

**Comment by robwierzbowski** [comment]
No worries!

**Comment by robwierzbowski** [comment]
Changing a lot on the way to 1.0, so many people are getting confused. I try to add all the common cases to the docs though.
