### ISSUE TITLE
TypeError: Arguments to path.join must be strings

### ISSUE THREAD

**Issue by fricks** [sindresorhus/gulp-ruby-sass#199]
Im getting this error when run gulp watch, whats wrong with my task?

gulp.task('css', function() {
  return gulp.src(config.sassPath + '/style.scss')
  .pipe(sass({
    style: 'normal', //normal, compressed
    loadPath: [
    './resources/sass',
    config.bowerDir + '/bootstrap-sass-official/assets/stylesheets',
    config.bowerDir + '/fontawesome/scss',
    config.bowerDir + '/Hover/scss',
    ]
  })
  .on("error", notify.onError(function (error) {
    return "Error: " + error.message;
  })))
  //.pipe(autoprefix('last 2 version'))
  .pipe(gulp.dest('./assets/css'));
});

**Comment by robwierzbowski** [comment]
https://github.com/sindresorhus/gulp-ruby-sass/issues/191

I'll be releasing 1.0 this Friday so there should be less confusion with the docs.

**Comment by fricks** [comment]
ok @robwierzbowski , but you can help me with this now?!

**Comment by fricks** [comment]
Thanks @robwierzbowski

**Comment by robwierzbowski** [comment]
Glob sources are implemented in this PR: https://github.com/sindresorhus/gulp-ruby-sass/pull/251, if you would like to test.
