### ISSUE TITLE
Can't add wildcards into sass() call

### ISSUE THREAD

**Issue by madebyreformat** [sindresorhus/gulp-ruby-sass#200]
I have used the new formatting as using `gulp.src` throws errors

```javascript
sass('src/scss/**/*.scss', { style: 'compressed' })
	.pipe( gulp.dest('build/css') );
```

but get the following error
```
[21:28:18] gulp-ruby-sass stderr: Errno::ENOENT: No such file or directory - src/scss/**/*.scss
  Use --trace for backtrace.
```

if i change to link to a single file eg. `src/scss/main.scss` it compiles fine, any ideas?

**Comment by UltCombo** [comment]
globbing is not supported yet #137

**Comment by JosefJezek** [comment]
:+1:

**Comment by swashcap** [comment]
:+1:

**Comment by robwierzbowski** [comment]
Let's make this the official issue for globbing. I'll add updates as the feature is added.

**Comment by robwierzbowski** [comment]
OK, looking at the docs it seems that we can pass multiple single files to the Sass CLI, which means it won't be too hard to implement globbing. Next on the list in *gulp + sass feature blitz 2015* :zap: :boom:

**Comment by robwierzbowski** [comment]
Progress here: https://github.com/sindresorhus/gulp-ruby-sass/pull/251. Will land soon.

**Comment by robwierzbowski** [comment]
PR #251 is ready for some testing. Any testing and code review by those that want glob sources would be greatly appreciated.

**Comment by ve3** [comment]
I have same problem it still does not work.

**Comment by robwierzbowski** [comment]
What is your sass task?

**Comment by ve3** [comment]
```js
var gulp = require('gulp');
var gutil = require('gulp-util');
var bower = require('bower');
var concat = require('gulp-concat');
var sass = require('gulp-sass');
var minifyCss = require('gulp-minify-css');
var rename = require('gulp-rename');
var sh = require('shelljs');

var paths = {
  sass: ['./www/lib/ionic/scss/**/*.scss']
};

gulp.task('default', ['sass']);

gulp.task('sass', function(done) {
  gulp.src('./www/lib/ionic/scss/ionic.app.scss')
    .pipe(sass())
    .on('error', sass.logError)
    .pipe(gulp.dest('./www/css/'))
    .pipe(minifyCss({
      keepSpecialComments: 0
    }))
    .pipe(rename({ extname: '.min.css' }))
    .pipe(gulp.dest('./www/css/'))
    .on('end', done);
});

gulp.task('watch', function() {
  gulp.watch(paths.sass, ['sass']);
});

gulp.task('install', ['git-check'], function() {
  return bower.commands.install()
    .on('log', function(data) {
      gutil.log('bower', gutil.colors.cyan(data.id), data.message);
    });
});

gulp.task('git-check', function(done) {
  if (!sh.which('git')) {
    console.log(
      '  ' + gutil.colors.red('Git is not installed.'),
      '\n  Git, the version control system, is required to download Ionic.',
      '\n  Download git here:', gutil.colors.cyan('http://git-scm.com/downloads') + '.',
      '\n  Once git is installed, run \'' + gutil.colors.cyan('gulp install') + '\' again.'
    );
    process.exit(1);
  }
  done();
});
```

It's fixed, sorry.
I just add /www/lib/ionic infront of /scss. 
Without /www/lib/ionic it works with `gulp sass` but not work with `gulp watch`.

**Comment by robwierzbowski** [comment]
👍🏽

On Thursday, February 4, 2016, vee w, <notifications@github.com> wrote:

> var gulp = require('gulp');var gutil = require('gulp-util');var bower = require('bower');var concat = require('gulp-concat');var sass = require('gulp-sass');var minifyCss = require('gulp-minify-css');var rename = require('gulp-rename');var sh = require('shelljs');
> var paths = {
>   sass: ['./www/lib/ionic/scss/**/*.scss']
> };
> gulp.task('default', ['sass']);
> gulp.task('sass', function(done) {
>   gulp.src('./www/lib/ionic/scss/ionic.app.scss')
>     .pipe(sass())
>     .on('error', sass.logError)
>     .pipe(gulp.dest('./www/css/'))
>     .pipe(minifyCss({
>       keepSpecialComments: 0
>     }))
>     .pipe(rename({ extname: '.min.css' }))
>     .pipe(gulp.dest('./www/css/'))
>     .on('end', done);
> });
> gulp.task('watch', function() {
>   gulp.watch(paths.sass, ['sass']);
> });
> gulp.task('install', ['git-check'], function() {
>   return bower.commands.install()
>     .on('log', function(data) {
>       gutil.log('bower', gutil.colors.cyan(data.id), data.message);
>     });
> });
> gulp.task('git-check', function(done) {
>   if (!sh.which('git')) {
>     console.log(
>       '  ' + gutil.colors.red('Git is not installed.'),
>       '\n  Git, the version control system, is required to download Ionic.',
>       '\n  Download git here:', gutil.colors.cyan('http://git-scm.com/downloads') + '.',
>       '\n  Once git is installed, run \'' + gutil.colors.cyan('gulp install') + '\' again.'
>     );
>     process.exit(1);
>   }
>   done();
> });
>
> It's fixed, sorry.
> I just add /www/lib/ionic infront of /scss.
> Without /www/lib/ionic it works with gulp sass but not work with gulp
> watch.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sindresorhus/gulp-ruby-sass/issues/200#issuecomment-179841831>
> .
>


-- 
Rob Wierzbowski
@robwierzbowski <http://twitter.com/#!/robwierzbowski>
http://github.com/robwierzbowski
http://robwierzbowski.com
