### ISSUE TITLE
Alpha.3 compiles sass from other projects.

### ISSUE THREAD

**Issue by andrewehipp** [sindresorhus/gulp-ruby-sass#201]
I've run into an issue at work where I have to jump between multiple projects each running gulp workflows. Any time I work on a project running gulp-ruby-sass 0.7.1 then switch to a project running 1.0.0-alpha.3 all my scss files from the 0.7.1 get copied over to the alpha.3 project when I run gulp.

Rolling back the affected projects to 0.7.1 removed the issue.

**Comment by robwierzbowski** [comment]
Use the container option. Thanks!

On Monday, February 16, 2015, andrewehipp <notifications@github.com> wrote:

> I've run into an issue at work where I have to jump between multiple
> projects each running gulp workflows. Any time I work on a project running
> gulp-ruby-sass 0.7.1 then switch to a project running 1.0.0-alpha.3 all my
> scss files from the 0.7.1 get copied over to the alpha.3 project when I run
> gulp.
>
> Rolling back the affected projects to 0.7.1 removed the issue.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sindresorhus/gulp-ruby-sass/issues/201>.
>


-- 
Rob Wierzbowski
@robwierzbowski <http://twitter.com/#!/robwierzbowski>
http://github.com/robwierzbowski
http://robwierzbowski.com

**Comment by andrewehipp** [comment]
Okay that would work.

Is the container not relative to the project root? And is it not cleaned out/deleted after being used?

**Comment by robwierzbowski** [comment]
It's relative to the OS temp directory, although I think you can give it an
absolute path of you want it somewhere else. Currently it's not cleaned out
after use -- eventually we'll need the last files at the beginning of every
run for sass caching.

On Monday, February 16, 2015, andrewehipp <notifications@github.com> wrote:

> Okay that would work.
>
> Is the container not relative to the project root? And is it not cleaned
> out/deleted after being used?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sindresorhus/gulp-ruby-sass/issues/201#issuecomment-74579548>
> .
>


-- 
Rob Wierzbowski
@robwierzbowski <http://twitter.com/#!/robwierzbowski>
http://github.com/robwierzbowski
http://robwierzbowski.com
