### ISSUE TITLE
Problem with npm install gulp-ruby-sass in Ubuntu 14.04 and node 0.13-pre

### ISSUE THREAD

**Issue by linuxonrails** [sindresorhus/gulp-ruby-sass#203]
npm install --save-dev gulp-ruby-sass
npm WARN package.json prueba@1.0.0 No description
npm WARN package.json prueba@1.0.0 No repository field.
npm WARN package.json prueba@1.0.0 No README data
npm WARN engine gulp-ruby-sass@1.0.0-alpha.3: wanted: {"node":">=0.10.0"} (current: {"node":"0.13.0-pre","npm":"2.5.1"})
npm ERR! Linux 3.13.0-32-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "--save-dev" "gulp-ruby-sass"
npm ERR! node v0.13.0-pre
npm ERR! npm  v2.5.1
npm ERR! code ETARGET

npm ERR! notarget No compatible version found: vinyl-fs@'>=0.3.7 <0.4.0'
npm ERR! notarget Valid install targets:
npm ERR! notarget ["0.0.1","0.0.2","0.1.0"]

**Comment by pipejesus** [comment]
Hi, this problem happens only if you use Node 0.13.0-pre . It doesn't appear when using 0.12, the current official build

**Comment by robwierzbowski** [comment]
It looks like we can update to a recently released 1.0.0. Can you test on your system and see if that solves the issue?

**Comment by robwierzbowski** [comment]
I just released a 1.0.1 version that includes updates to vinyl-fs. Can you install the latest gulp-ruby-sass and let me know if the problem persists?
