### ISSUE TITLE
compile cost much time

### ISSUE THREAD

**Issue by s6323859** [sindresorhus/gulp-ruby-sass#205]
There are just 10 sass files in my project. 
sass always compile cost 4.19s~4.5s (compass&susy is enable)
that feel too bad

**Comment by arthurvr** [comment]
Yeah that's definitely a thing when using Ruby Sass :smiling_imp: You'll see it takes that much time when using it with the raw gem too. If that's possible, go take a look at [LibSass](https://github.com/sass/libsass).

**Comment by robwierzbowski** [comment]
Can you check if there's a difference between running the Sass gem by itself and running gulp-ruby-sass? If there is, please re-open, but if they are similar it's just the amount of time your Sass takes to compile.
