### ISSUE TITLE
Multiple instances of gulp-ruby-sass causes ENOENT error

### ISSUE THREAD

**Issue by siliconalchemy** [sindresorhus/gulp-ruby-sass#207]
If running multiple instances of gulp (for example multiple developers each running gulp instance to get different browser-sync instance), then gulp-ruby-sass errors as follows because one instance deletes the temporary container while the other one is using it:

[16:39:47] gulp-ruby-sass stderr: /usr/local/share/gems/gems/sass-3.4.11/lib/sass/exec/base.rb:182:in `initialize': No such file or directory - styles.css (Errno::ENOENT)
	from /usr/local/share/gems/gems/sass-3.4.11/lib/sass/exec/base.rb:182:in `open'
	from /usr/local/share/gems/gems/sass-3.4.11/lib/sass/exec/base.rb:182:in `open_file'
	from /usr/local/share/gems/gems/sass-3.4.11/lib/sass/exec/base.rb:171:in `write_output'
	from /usr/local/share/gems/gems/sass-3.4.11/lib/sass/exec/sass_scss.rb:415:in `run'
	from /usr/local/share/gems/gems/sass-3.4.11/lib/sass/exec/sass_scss.rb:63:in `process_result'
	from /usr/local/share/gems/gems/sass-3.4.11/lib/sass/exec/base.rb:52:in `parse'
	from /usr/local/share/gems/gems/sass-3.4.11/lib/sass/exec/base.rb:19:in `parse!'
	from /usr/local/share/gems/gems/sass-3.4.11/bin/sass:13:in `<top (required)>'
	from /usr/local/bin/sass:23:in `load'
	from /usr/local/bin/sass:23:in `<main>'

Setting container doesn't work because multiple instances will still use the same container argument.  Ideally, it would use a random temporary directory name for the container (eg. /tmp/gulp-ruby-sass-xyz123) so multiple instances can run without clashing.

**Comment by pyrsmk** [comment]
I have the same error with only one instance of Gulp running. I have 4 CSS files to generate so I run 4 `sass` but I need to re-run the task several times to achieve the generation of the 4 files (because of the error above). I think it can be resolved by using globs are by being able to run tasks synchronously (which is not practical at all with Gulp way, or even `run-sequence`).

Here's what I am doing : 

```js
fs.readdir( './components', function( err, list ) {
	if( !err ){
		list.forEach( function( dir ) {
			if( dir.charAt(0) == '@' ) {
				var name = dir.substring( 1 ),
					path = './components/' + dir + '/' + name + '.scss';
				if( fs.existsSync(path) ) {
					sass( path, { loadPath: [ './scss/', './components/' ] } )
						.pipe( plumber() )
						.pipe( cache( 'css' ) )
						.pipe( $if( prod, uncss( { html: [ conf[ dir ] ] } ) ) )
						.pipe( $if( prod, csso() ) )
						.pipe( gulp.dest( './' ) )
						.pipe( size( { gzip: true } ) );
				}
			}
		});
	}
} );
```

**Comment by robwierzbowski** [comment]
Why does container not work? Are these multiple developers working on the
same computer, or?

On Friday, March 13, 2015, Aurélien Delogu <notifications@github.com> wrote:

> I have the same error with only one instance of Gulp running. I have 4 CSS
> files to generate so I run 4 sass but I need to re-run the task several
> times to achieve the generation of the 4 files (because of the error
> above). I think it can be resolved by using globs are by being able to run
> tasks synchronously (which is not practical at all with Gulp way, or even
> run-sequence).
>
> Here's what I am doing :
>
> fs.readdir( './components', function( err, list ) {
>     if( !err ){
>         list.forEach( function( dir ) {
>             if( dir.charAt(0) == '@' ) {
>                 var name = dir.substring( 1 ),
>                     path = './components/' + dir + '/' + name + '.scss';
>                 if( fs.existsSync(path) ) {
>                     sass( path, { loadPath: [ './scss/', './components/' ] } )
>                         .pipe( plumber() )
>                         .pipe( cache( 'css' ) )
>                         .pipe( $if( prod, uncss( { html: [ conf[ dir ] ] } ) ) )
>                         .pipe( $if( prod, csso() ) )
>                         .pipe( gulp.dest( './' ) )
>                         .pipe( size( { gzip: true } ) );
>                 }
>             }
>         });
>     }
> } );
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sindresorhus/gulp-ruby-sass/issues/207#issuecomment-78884567>
> .
>


-- 
Rob Wierzbowski
@robwierzbowski <http://twitter.com/#!/robwierzbowski>
http://github.com/robwierzbowski
http://robwierzbowski.com

**Comment by pyrsmk** [comment]
Container?

**Comment by UltCombo** [comment]
@pyrsmk https://github.com/sindresorhus/gulp-ruby-sass#container

**Comment by pyrsmk** [comment]
Not really obvious without any example, but thanks, I'll try this!

**Comment by pyrsmk** [comment]
And now, all is working as expected. Thanks a lot!

**Comment by siliconalchemy** [comment]
I don't think this helps my situation where there are multiple instances of the same task being run - yes, multiple developers on the same server.  If the container name could be randomised that might work.

**Comment by robwierzbowski** [comment]
You can randomize the container in your gulpfile by setting it to the
result of a function that returns a random string. I'm working towards
implementing Sass caching which is going to need the same container between
runs. I don't think many developers on the same remote box using the same
gulpfile is a common use case, so I probably won't add any code to support
it in the module itself.

Does that work for you?

Rob Wierzbowski
@robwierzbowski <http://twitter.com/#!/robwierzbowski>
http://github.com/robwierzbowski
http://robwierzbowski.com

**Comment by siliconalchemy** [comment]
Yup that seems to work, thanks!  Seeing as the containers are transient, why not randomise the names by default?  Wouldn't hurt would it?

**Comment by UltCombo** [comment]
@siliconalchemy that would break the Sass caching mechanism IIRC.
