### ISSUE TITLE
Breaking the build on SASS stderr output

### ISSUE THREAD

**Issue by evpaassen** [sindresorhus/gulp-ruby-sass#209]
I'd like to break my build when `sass` encounters a syntax error (or whenever `sass` outputs something to stderr), but It seems these errors are only logged by this plugin:

```javascript
sass.stderr.on('data', function (data) {
	var msg = removePaths(data, [tempDir, relativeCompileDir]).trim();

	if (noBundleSassMatcher.test(msg)) {
		stream.emit('error', createErr(bundleErrMsg, {showStack: false}));
	} else if (!noSassMatcher.test(msg)) {
		gutil.log('gulp-ruby-sass: stderr:', msg);
	}
});
```

This prevents me from handling these errors correctly. Breaking the build would be useful especially when using continuous integration. Could there be a way to handle such errors somehow?

**Comment by evpaassen** [comment]
This seems to happen only if `stopOnError: true`, so I'll set that to `false` (default) then.

**Comment by robwierzbowski** [comment]
A little confused — you say that `stopOnError` does not stop the sass compilation? I agree, we can add an option for breaking the build if a compile error or the like occurs.

**Comment by robwierzbowski** [comment]
Working on this now. Some things are logged to stderr that we don't want to break the build for (warnings and debug statements). Stdout actually contains syntax errors, which I'm adding an option to throw as errors instead of logging. Does that cover your request here?

**Comment by evpaassen** [comment]
Sorry for being a little quiet lately. Finally I found some time to dig a bit deeper into this, but I got a little confused about error handling too.

When creating a build (and thus transpiling scss), I want the build to fail explicitly when a subtask fails. I created a little test project to demonstrate my problem: https://github.com/evpaassen/gulp-ruby-sass-error-handling-test. The scss files contain errors.



##### Using version `1.0.0-alpha.3` and `stopOnError: false`: build breaks like I would expect
```
$ gulp sass
[13:03:34] Using gulpfile d:\projects\rubysass-error-test\gulpfile.js
[13:03:34] Starting 'sass'...
[13:03:34] gulp-ruby-sass stdout: directory
[13:03:34] CUSTOM ERROR HANDLER TRIGGERED
[13:03:34] Error in plugin 'gulp-ruby-sass'
Message:
    error ./sass/nonexistinginclude.scss (Line 1: File to import not found or unreadable: nonexistingfile.
Load path: d:/projects/rubysass-error-test/sass)
```

##### Using version `1.0.0-alpha.3` and `stopOnError: true`: sass compilation stops, but custom error handler is not triggered
```
$ gulp sass
[13:04:12] Using gulpfile d:\projects\rubysass-error-test\gulpfile.js
[13:04:12] Starting 'sass'...
[13:04:13] gulp-ruby-sass stderr: Error: File to import not found or unreadable: nonexistingfile.
       Load path: d:/projects/rubysass-error-test/sass
        on line 1 of ./sass/nonexistinginclude.scss
  Use --trace for backtrace.
[13:04:13] Finished 'sass' after 792 ms
```

##### Using version `1.0.5` and `stopOnError: false`: sass compilation continues, but custom error handler is not triggered
```
$ gulp sass
[13:11:20] Using gulpfile d:\projects\rubysass-error-test\gulpfile.js
[13:11:20] Starting 'sass'...
[13:11:21] directory ./
[13:11:21] error ./sass/nonexistinginclude.scss (Line 1: File to import not found or unreadable: nonexistingfile.
Load path: d:/projects/rubysass-error-test/sass)
[13:11:21] error ./sass/syntaxerror.scss (Line 1: Invalid CSS after "bla bla bla": expected "{", was ";")
[13:11:21] Finished 'sass' after 794 ms
```

##### Using version `1.0.5` and `stopOnError: true`: sass compilation stops, but custom error handler is not triggered
```
$ gulp sass
[13:09:18] Using gulpfile d:\projects\rubysass-error-test\gulpfile.js
[13:09:18] Starting 'sass'...
[13:09:19] directory ./
[13:09:19] Error: File to import not found or unreadable: nonexistingfile.
       Load path: d:/projects/rubysass-error-test/sass
        on line 1 of ./sass/nonexistinginclude.scss
  Use --trace for backtrace.
[13:09:19] Finished 'sass' after 773 ms
```

Am I doing something wrong here?

**Comment by evpaassen** [comment]
> Working on this now. Some things are logged to stderr that we don't want to break the build for (warnings and debug statements). Stdout actually contains syntax errors, which I'm adding an option to throw as errors instead of logging. Does that cover your request here?

Yes, I think that probably would cover it. Thank you.

**Comment by robwierzbowski** [comment]
Ok! I can add that. Thanks for the detailed breakdown.

On Tuesday, April 28, 2015, Erik van Paassen <notifications@github.com>
wrote:

> Working on this now. Some things are logged to stderr that we don't want
> to break the build for (warnings and debug statements). Stdout actually
> contains syntax errors, which I'm adding an option to throw as errors
> instead of logging. Does that cover your request here?
>
> Yes, I think that probably would cover it. Thank you.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sindresorhus/gulp-ruby-sass/issues/209#issuecomment-97026016>
> .
>


-- 
Rob Wierzbowski
@robwierzbowski <http://twitter.com/#!/robwierzbowski>
http://github.com/robwierzbowski
http://robwierzbowski.com

**Comment by HugoGiraudel** [comment]
What is the status on this?

**Comment by robwierzbowski** [comment]
I think this is actually implemented. See the logger file here: https://github.com/sindresorhus/gulp-ruby-sass/blob/master/logger.js. Does it throw errors for all the output that you would expect it to?

**Comment by HugoGiraudel** [comment]
I have been playing with this yesterday night and I can confirm @evpaassen's results. Even with `stopOnError` set to `true`, the Gulp process does not exist automatically.

The `gulp-sass` plugin is doing it correctly as far as I can tell. If a Sass error occurs and the `logErrOnConsole` (what a poorly chosen name) option is not set to `true`, the Gulp process exists properly.

**Comment by evpaassen** [comment]
> I think this is actually implemented. See the logger file here: https://github.com/sindresorhus/gulp-ruby-sass/blob/master/logger.js. Does it throw errors for all the output that you would expect it to?

The latest commit to this file is already included in the v1.0.5 release, which I tested here: https://github.com/sindresorhus/gulp-ruby-sass/issues/209#issuecomment-97022629. So no, afaik this has not been fixed yet.

I'm still using version 1.0.0-alpha.3 so I can attach a custom error handler which calls `process.exit(1);` (with `stopOnError` set to `false`, otherwise it's broken). In version 1.0.5, the custom error handler isn't called at all.

**Comment by evpaassen** [comment]
Rob, earlier on you suggested:
> Stdout actually contains syntax errors, which I'm adding an option to throw as errors instead of logging.

I'd like to emphasize that I think this would be the way to go. This hasn't been implemented yet, right?

**Comment by robwierzbowski** [comment]
That part has been implemented. All "errors" should throw an error event,
but yeah I can see that it doesn't stop compilation right away. I'll look
into this further.

On Friday, June 5, 2015, Erik van Paassen <notifications@github.com> wrote:

> Rob, earlier on you suggested:
>
> Stdout actually contains syntax errors, which I'm adding an option to
> throw as errors instead of logging.
>
> I'd like to emphasize that I think this would be the way to go. This
> hasn't been implemented yet, right?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sindresorhus/gulp-ruby-sass/issues/209#issuecomment-109233876>
> .
>


-- 
Rob Wierzbowski
@robwierzbowski <http://twitter.com/#!/robwierzbowski>
http://github.com/robwierzbowski
http://robwierzbowski.com

**Comment by robwierzbowski** [comment]
Aaaand, here's where I was implementing this:

https://github.com/sindresorhus/gulp-ruby-sass/commit/dadd2f5d73b1577976771370f12590336e1ec0d9

See the note here: https://github.com/sindresorhus/gulp-ruby-sass/blob/dadd2f5d73b1577976771370f12590336e1ec0d9/test.js#L266-L267

Right now we're reading stderr and stdout, but sometimes Sass or gulp give the log in a chunk that includes both normal logging and Sass errors. :trollface: :-1:. Nex3 suggested that we use the ruby bindings, which I have to investigate. I'm not sure how much of this plugin will need to be rewritten in order to make that work. So on the table for now... PR's accepted.

**Comment by robwierzbowski** [comment]
Another option would be to break each clump of logging on line breaks, then run the regex on each line, but that seems super ugly.

**Comment by tupton** [comment]
I think something simpler would suffice here. If the sass process exits with a non-zero exit code, you could emit an error that contains stdout, stderr, and the exit code and then let users decide what to do with that information.

**Comment by robwierzbowski** [comment]
If I remember correctly, Sass doesn't emit a non-zero exit code when Sass
files error. You're expected to see the errors in the browser window that
loads the Sass file.

Rob Wierzbowski
@robwierzbowski <http://twitter.com/#!/robwierzbowski>
http://github.com/robwierzbowski
http://robwierzbowski.com

**Comment by tupton** [comment]
```
❯ sass --version
Sass 3.4.13 (Selective Steve)
❯ cat test.scss
body {
    dne:
    background-color: #000;
}
❯ sass test.scss:test.css
Error: Invalid CSS after "...ackground-color": expected ";", was ": #000;"
        on line 3 of test.scss
  Use --trace for backtrace.
❯ echo $?
65
❯ sass .:. --update
      error ./test.scss (Line 3: Invalid CSS after "...ackground-color": expected ";", was ": #000;")
❯ echo $?
1
```

**Comment by robwierzbowski** [comment]
Cool cool. I stand corrected.

**Comment by robwierzbowski** [comment]
@tupton Looking at this today again. I don't think that would help OP since we'd be waiting for the end of the stream before logging anything, not breaking the build when an 'error-ish' message is emitted.

Emitting a separate error at the end of a stream if there are any error-ish messages is a decent idea. I'll look into that.

**Comment by robwierzbowski** [comment]
@evpaassen The Sass `stopOnError` property seems to do most of what you need.

gulp task:

```js
gulp.task('sass', function() {
  return sass('source', { sourcemap: true, verbose: true, stopOnError: true })
  .on('error', function (err) {
    console.error('Error!', err.message);
  })
  .pipe(gulp.dest('result'));
});
```

`source` directory contains the files:

```
a.scss, b.scss, c.scss, d.scss
```

b.scss has an error in it. When I run `gulp sass`, only a.scss is output into the result directory.

**Comment by robwierzbowski** [comment]
The second part of your request if I understand correctly is for GRS to emit errors when Sass outputs a compile or syntax error, AND have the build break on error. Looking through your example project now.

Sorry, haven't looked at this issue in a while. Not sure there's an easy fix, but I'll see what I can do.

**Comment by evpaassen** [comment]
I just want to make sure my sass task fails if a compile/syntax error arises. I don't really care if it fails early or at the end of the stream. It's just that I want my build chain to fail if there's an error. I'm still using the 1.0.0-alpha.3 version as it allows me to do so, in contrast to version 1.0.5.

**Comment by evpaassen** [comment]
This is an example of how I currently use my custom error handler with version 1.0.0-alpha.3: 
```javascript
var gulp = require('gulp');
var sass = require('gulp-ruby-sass');
var gutil = require('gulp-util');

gulp.task('sass', function () {
    return sass('source/', {
        style: 'compressed'
    })
    .on('error', function(err) {
        gutil.log(err.toString());
        process.exit(1);
    })
    .pipe(gulp.dest('result'));
});
```
This ensures tasks depending on the sass task are not being executed.

**Comment by robwierzbowski** [comment]
Thanks. Yeah, I think we may be able to do this with @tupton's suggestion (thanks @tupton), or by parsing each stdout/err line individually for the string `error`. Will give it a shot today.

**Comment by evpaassen** [comment]
Thanks, great! Checking for a non-zero exit code, like @tupton mentioned, seems like a clean solution to me.

**Comment by robwierzbowski** [comment]
Do you want the messages that may have caused the error, or is the current logging sufficient?

**Comment by robwierzbowski** [comment]
Working on an `emitErrorOnSassError` option. Option name suggestions welcome, that name is horrible.

**Comment by evpaassen** [comment]
> Do you want the messages that may have caused the error, or is the current logging sufficient?

Current logging is sufficient to me.

**Comment by robwierzbowski** [comment]
What do you think about the name `emitCompilationErrors`?

**Comment by evpaassen** [comment]
Should be fine, or `emitCompileErrors`?

**Comment by robwierzbowski** [comment]
Shorter is better :+1:

**Comment by robwierzbowski** [comment]
@evpaassen, check out the linked PR above :arrow_up:. Can you code review, maybe test on your system?

**Comment by evpaassen** [comment]
Looks good.

**Comment by robwierzbowski** [comment]
Fixed and published as `1.3.0`!

**Comment by robwierzbowski** [comment]
No problem. Glad I could help.

**Comment by tupton** [comment]
Just wanted to follow up here and say thanks for this change. This does exactly what I wanted, too.

**Comment by robwierzbowski** [comment]
Excellent! I might try and make it more atomic in the future.

On Monday, September 7, 2015, Thomas Upton <notifications@github.com> wrote:

> Just wanted to follow up here and say thanks for this change. This does
> exactly what I wanted, too.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sindresorhus/gulp-ruby-sass/issues/209#issuecomment-138376795>
> .
>


-- 
Rob Wierzbowski
@robwierzbowski <http://twitter.com/#!/robwierzbowski>
http://github.com/robwierzbowski
http://robwierzbowski.com
