### ISSUE TITLE
TypeError on runtime

### ISSUE THREAD

**Issue by MARS1** [sindresorhus/gulp-ruby-sass#210]
Keep getting this error with my sass

[12:31:44] 'sass' errored after 1.86 ms
[12:31:44] TypeError: Arguments to path.join must be strings
    at path.js:360:15
    at Array.filter (native)
    at Object.exports.join (path.js:358:36)
    at module.exports (/Users/mberta/Desktop/DEV/Sky Child Care/2-marketingSite/skychildcare-com/node_modules/gulp-ruby-sass/index.js:65:15)
    at Gulp.<anonymous> (/Users/mberta/Desktop/DEV/Sky Child Care/2-marketingSite/skychildcare-com/gulpfile.js:34:9)
    at module.exports (/Users/mberta/Desktop/DEV/Sky Child Care/2-marketingSite/skychildcare-com/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:34:7)
    at Gulp.Orchestrator._runTask (/Users/mberta/Desktop/DEV/Sky Child Care/2-marketingSite/skychildcare-com/node_modules/gulp/node_modules/orchestrator/index.js:273:3)
    at Gulp.Orchestrator._runStep (/Users/mberta/Desktop/DEV/Sky Child Care/2-marketingSite/skychildcare-com/node_modules/gulp/node_modules/orchestrator/index.js:214:10)
    at Gulp.Orchestrator.start (/Users/mberta/Desktop/DEV/Sky Child Care/2-marketingSite/skychildcare-com/node_modules/gulp/node_modules/orchestrator/index.js:134:8)
    at /usr/local/lib/node_modules/gulp/bin/gulp.js:129:20

All I have in my gulpfile.js for Sass is this:

// Styles Task
// Sass
gulp.task('sass' , function(){
  return gulp.src('scss/**/*.scss')
  .pipe(styles())
  .pipe(gulp.dest('css'));
});

**Comment by robwierzbowski** [comment]
Check closed issues, read the updated documentation. Grs doesn't use
gulp.src anymore.

On Thursday, March 12, 2015, MARS <notifications@github.com> wrote:

> Keep getting this error with my sass
>
> [12:31:44] 'sass' errored after 1.86 ms
> [12:31:44] TypeError: Arguments to path.join must be strings
> at path.js:360:15
> at Array.filter (native)
> at Object.exports.join (path.js:358:36)
> at module.exports (/Users/mberta/Desktop/DEV/Sky Child
> Care/2-marketingSite/skychildcare-com/node_modules/gulp-ruby-sass/index.js:65:15)
> at Gulp. (/Users/mberta/Desktop/DEV/Sky Child
> Care/2-marketingSite/skychildcare-com/gulpfile.js:34:9)
> at module.exports (/Users/mberta/Desktop/DEV/Sky Child
> Care/2-marketingSite/skychildcare-com/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:34:7)
> at Gulp.Orchestrator._runTask (/Users/mberta/Desktop/DEV/Sky Child
> Care/2-marketingSite/skychildcare-com/node_modules/gulp/node_modules/orchestrator/index.js:273:3)
> at Gulp.Orchestrator._runStep (/Users/mberta/Desktop/DEV/Sky Child
> Care/2-marketingSite/skychildcare-com/node_modules/gulp/node_modules/orchestrator/index.js:214:10)
> at Gulp.Orchestrator.start (/Users/mberta/Desktop/DEV/Sky Child
> Care/2-marketingSite/skychildcare-com/node_modules/gulp/node_modules/orchestrator/index.js:134:8)
> at /usr/local/lib/node_modules/gulp/bin/gulp.js:129:20
>
> All I have in my gulpfile.js for Sass is this:
>
> // Styles Task
> // Sass
> gulp.task('sass' , function(){
> return gulp.src('scss/**/*.scss')
> .pipe(styles())
> .pipe(gulp.dest('css'));
> });
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sindresorhus/gulp-ruby-sass/issues/210>.
>


-- 
Rob Wierzbowski
@robwierzbowski <http://twitter.com/#!/robwierzbowski>
http://github.com/robwierzbowski
http://robwierzbowski.com

**Comment by MARS1** [comment]
ok it doesn't throw errors when I write the task like this:

// Styles Task
// Sass
gulp.task('sass' , function() {
  return
    $.rubySass('scss/**/*.scss')
    .on('error' , function(err) {
      console.log('Error! ' , err.message);
    })
    .pipe(prefix('last 2 versions'))
    .pipe(rename('app.css'))
    .pipe(gulp.dest('css/'));
});


But it doesn't compile my sass into it's main file either. 

For example I have everything being imported into app.scss and my dest directory is 'css/'. So the expected behavior is an app.css file with all of my compiled css, but I don't get that, even though Sass starts and finishes now. Any ideas?

Thank you.

**Comment by robwierzbowski** [comment]
https://github.com/sindresorhus/gulp-ruby-sass/tree/rw/1.0#important

Grs doesn't support globs yet. It's all in the docs.

**Comment by MARS1** [comment]
ok then I need to find out what globs are. Thanks.

**Comment by robwierzbowski** [comment]
No problem. Globs are strings like `foo/**/bar` with the stars and little regex like patterns in them.

**Comment by robwierzbowski** [comment]
Glob sources are implemented in this PR: https://github.com/sindresorhus/gulp-ruby-sass/pull/251, if you would like to test.
