### ISSUE TITLE
I can use this gulp.watch and ruby-sass？

### ISSUE THREAD

**Issue by nimojs** [sindresorhus/gulp-ruby-sass#212]
I want watch `src/sass/**/*.scss` automatically recompile。

```js
var gulp = require('gulp');
var sass = require('gulp-ruby-sass');


gulp.task('default', function () {
    gulp.watch('src/sass/**/*.scss', function (event) {
        var path = event.path
                        .replace(__dirname,'')
                        .replace(/^\//,'');
        // src/sass/demo.scss

        var dist = path.replace(/[^\/]+$/,'').replace(/^src\/sass/,'dist/css');
        // dist/css/

        console.log('Change:' + path);
        console.log('Dest:' + dist);
        
        return sass(path)
            .on('error', function (err) {
              console.error('Error!', err.message);
            })
            .pipe(gulp.dest(dist));
    });
})
```

I can write like this?  There's a better way?

**Comment by robwierzbowski** [comment]
Globbing is not supported yet, but you can watch a directory (just like
with the Sass gem).  Try using `src/sass/`.

On Wednesday, March 25, 2015, NimoChu <notifications@github.com> wrote:

> I want watch src/sass/**/*.scss automatically recompile。
>
> var gulp = require('gulp');var sass = require('gulp-ruby-sass');
>
>
> gulp.task('default', function () {
>     gulp.watch('src/sass/**/*.scss', function (event) {
>         var path = event.path
>                         .replace(__dirname,'')
>                         .replace(/^\//,'');
>         // src/sass/demo.scss
>
>         var dist = path.replace(/[^\/]+$/,'').replace(/^src\/sass/,'dist/css');
>         // dist/css/
>
>         console.log('Change:' + path);
>         console.log('Dest:' + dist);
>
>         return sass(path)
>             .on('error', function (err) {
>               console.error('Error!', err.message);
>             })
>             .pipe(gulp.dest(dist));
>     });
> })
>
> I can write like this? There's a better way?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sindresorhus/gulp-ruby-sass/issues/212>.
>


-- 
Rob Wierzbowski
@robwierzbowski <http://twitter.com/#!/robwierzbowski>
http://github.com/robwierzbowski
http://robwierzbowski.com

**Comment by nimojs** [comment]
Excuse,I don't understand what you mean.

I using `src/sass/` `gulp.watch` doesn't work。

```js
gulp.watch('src/sass/', function (event) {
```

versions:

- gulp v3.8.11
- node v0.12.1
- gulp-ruby-sass v1.0.1

**Comment by nimojs** [comment]
But using `src/sass/**/*.scss` can be work.

```js
gulp.watch('src/sass/**/*.scss', function (event) {
```

```
Change:src/sass/a.scss
Dest:dist/css/
Change:src/sass/demo.scss
Dest:dist/css/
```

**Comment by robwierzbowski** [comment]
Exactly :)

On Wednesday, March 25, 2015, NimoChu <notifications@github.com> wrote:

> But using src/sass/**/*.scss can be work.
>
> gulp.watch('src/sass/**/*.scss', function (event) {
>
> Change:src/sass/a.scss
> Dest:dist/css/
> Change:src/sass/demo.scss
> Dest:dist/css/
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sindresorhus/gulp-ruby-sass/issues/212#issuecomment-86119685>
> .
>


-- 
Rob Wierzbowski
@robwierzbowski <http://twitter.com/#!/robwierzbowski>
http://github.com/robwierzbowski
http://robwierzbowski.com

**Comment by robwierzbowski** [comment]
Use the directory for sass, and the glob for gulp watch.

On Wednesday, March 25, 2015, Rob Wierzbowski <rob.wierzbowski@gmail.com>
wrote:

> Exactly :)
>
> On Wednesday, March 25, 2015, NimoChu <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:
>
>> But using src/sass/**/*.scss can be work.
>>
>> gulp.watch('src/sass/**/*.scss', function (event) {
>>
>> Change:src/sass/a.scss
>> Dest:dist/css/
>> Change:src/sass/demo.scss
>> Dest:dist/css/
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/sindresorhus/gulp-ruby-sass/issues/212#issuecomment-86119685>
>> .
>>
>
>
> --
> Rob Wierzbowski
> @robwierzbowski <http://twitter.com/#!/robwierzbowski>
> http://github.com/robwierzbowski
> http://robwierzbowski.com
>
>

-- 
Rob Wierzbowski
@robwierzbowski <http://twitter.com/#!/robwierzbowski>
http://github.com/robwierzbowski
http://robwierzbowski.com

**Comment by nimojs** [comment]
Thank you, so I can be like the example above uses gulp-ruby-sass？

**Comment by robwierzbowski** [comment]
Looking at your example again, it's very complex. I would suggest:

```
gulp.task('sass', function() {
    return sass('src/sass/') 
    .on('error', function (err) {
      console.error('Error!', err.message);
   })
    .pipe(gulp.dest('dist/css'));
});

gulp.watch('src/sass/**/*.scss', 'sass')
```

**Comment by robwierzbowski** [comment]
Try looking at the examples in the readme on this repository, and also the gulp.watch examples. Maybe search for some example gulpfiles too, to see how people put them together. 

The Web Starter Kit is a good one to use as an example: https://github.com/google/web-starter-kit/blob/master/gulpfile.js

**Comment by nimojs** [comment]
`return sass('src/sass/') ` will compile all the files,I just want to compile the modified files

```
[09:45:24] Using gulpfile ~/Documents/code/demo/gulp/gulpfile.js
[09:45:24] Starting 'default'...
[09:45:24] Finished 'default' after 11 ms
[09:45:39] Starting 'sass'...
[09:45:39] gulp-ruby-sass stdout: directory
[09:45:39] gulp-ruby-sass stdout: write a.css
[09:45:39] gulp-ruby-sass stdout: write demo.css
[09:45:39] gulp-ruby-sass stdout: directory page
[09:45:39] gulp-ruby-sass stdout: write page/page-a.css
[09:45:39] Finished 'sass' after 267 ms
```

In this case, change `a.scss`, It will compile `a.scss` `demo.scss` `page/page-a.scss`

**Comment by robwierzbowski** [comment]
True. I'm working on recompiling just the changed files in https://github.com/sindresorhus/gulp-ruby-sass/issues/111.

We used to compile every file individually, which let us only compile changed files but was very bad for performance. Sass expects a directory or a single file, and has its own caching mechanism to deal with incremental builds. My plan is to use Sass caching and not gulp for incremental builds.

**Comment by nimojs** [comment]
I support your plan.
Thank for your help, Awesome work.
![](http://img1.imgtn.bdimg.com/it/u=3456984372,2068754285&fm=23&gp=0.jpg)
