### ISSUE TITLE
Implement Multiple extends

### ISSUE THREAD

**Issue by stafili** [sindresorhus/gulp-ruby-sass#213]
Implement multiple extends as described here : [SASS_REFERENCE]( http://sass-lang.com/documentation/file.SASS_REFERENCE.html#multiple_extends)

> Multiple extends can also be written using a comma-separated list of selectors. For example, @extend .error, .attention is the same as @extend .error; @extend.attention.

**Comment by robwierzbowski** [comment]
This plugin just wraps sass. In order for that to work you just need to
have a sass version available to your shell in the gulpfile directory that
supports it.

On Saturday, March 28, 2015, stafili <notifications@github.com> wrote:

> Implement multiple extends as described here : SASS_REFERENCE
> <http://sass-lang.com/documentation/file.SASS_REFERENCE.html#multiple_extends>
>
> Multiple extends can also be written using a comma-separated list of
> selectors. For example, @extend <https://github.com/extend> .error,
> .attention is the same as @extend <https://github.com/extend> .error;
> @extend.attention.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sindresorhus/gulp-ruby-sass/issues/213>.
>


-- 
Rob Wierzbowski
@robwierzbowski <http://twitter.com/#!/robwierzbowski>
http://github.com/robwierzbowski
http://robwierzbowski.com
