### ISSUE TITLE
sourcemaps error

### ISSUE THREAD

**Issue by juancabrera** [sindresorhus/gulp-ruby-sass#214]
I'm getting this error by default (on version 1.0.1 ).
I also got this error even with I set sourcemaps to false. ```{ sourcemap: false }```

```
[16:06:29] gulp-ruby-sass stderr: OptionParser::InvalidOption: invalid option: --sourcemap=none
  Use --trace for backtrace.
```

**Comment by robwierzbowski** [comment]
What version of Sass are you using? Does it meet the requirements in the readme?

**Comment by juancabrera** [comment]
That was the error, had a "old" version of sass.
