### ISSUE TITLE
OptionParser::InvalidOption: invalid option: --sourcemap=none

### ISSUE THREAD

**Issue by gmjorge** [sindresorhus/gulp-ruby-sass#220]
I'm using *gulp-ruby-sass* version 1.0.1 with a single configuration and not source map (`{sourcemap: false}` and I'm getting the follow error:

`gulp-ruby-sass stderr: OptionParser::InvalidOption: invalid option: --sourcemap=none`

any idea?

**Comment by robwierzbowski** [comment]
Check out closed issues and the readme. Does your version of Sass meet the version requirements of this plugin?

**Comment by gmjorge** [comment]
My bad. I should look into close issue first. I'm using a old sass version. Thanks too much @robwierzbowski :+1:

**Comment by robwierzbowski** [comment]
No problem :).

**Comment by nivassri** [comment]
OptionParser::InvalidOption: invalid option: --exclude-ruby-options=includePaths
  Use --trace for backtrace.

How can in fix this error

**Comment by robwierzbowski** [comment]
OptionParser is part of the Sass gem. It looks like you're passing
something to the gem that it doesn't understand.

I'm not sure what that option is, but you might try include-paths.

On Friday, October 30, 2015, srinivas <notifications@github.com
<javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:

> OptionParser::InvalidOption: invalid option:
> --exclude-ruby-options=includePaths
> Use --trace for backtrace.
>
> How can in fix this error
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sindresorhus/gulp-ruby-sass/issues/220#issuecomment-152550144>
> .
>


-- 
Rob Wierzbowski
@robwierzbowski <http://twitter.com/#!/robwierzbowski>
http://github.com/robwierzbowski
http://robwierzbowski.com

**Comment by robwierzbowski** [comment]
If I run `sass -h` to get Sass command line options I don't see `exclude-ruby-options`. 

gulp-ruby-sass understands a few custom options (documented in the readme) and Sass options.

**Comment by torresomar** [comment]
Updating Sass gem solved it for me :+1:
