### ISSUE TITLE
Logger broken

### ISSUE THREAD

**Issue by ayhankuru** [sindresorhus/gulp-ruby-sass#222]
1.0.2 version logger module broken 
![ekran goruntusu - 2015-04-26 20 03 49](https://cloud.githubusercontent.com/assets/2834954/7338266/8ea165de-ec4f-11e4-9cb3-6de7710707e4.png)
![ekran goruntusu - 2015-04-26 20 05 29](https://cloud.githubusercontent.com/assets/2834954/7338275/a4a2ed9e-ec4f-11e4-8298-29916c450613.png)

**Comment by robwierzbowski** [comment]
Ah, how did this happen. Give me a minute.

**Comment by UltCombo** [comment]
@robwierzbowski https://github.com/sindresorhus/gulp-ruby-sass/blob/e55df9f1f9b340673de1bb3b25512813201ddd57/package.json#L25

**Comment by UltCombo** [comment]
Oh I was late, you already fixed it hahah.

**Comment by ayhankuru** [comment]
@robwierzbowski @UltCombo that's right, or replace **main:"index.js"**

**Comment by robwierzbowski** [comment]
OK, all should be fixed up now. Thanks for the quick report, and sorry about the oversight.
