### ISSUE TITLE
It used to work with gulp.src and globbing?

### ISSUE THREAD

**Issue by yani-** [sindresorhus/gulp-ruby-sass#223]
The new version tries to skip gulp.src step but it doesn't have support for globbing yet. Is there a way to use gulp.src until globbing support is implemented?

**Comment by robwierzbowski** [comment]
No there isn't. Can you use a directory? If you give me an example file
structure I can help you set up the task in the way that you would with the
sass command line tool.

On Tuesday, April 28, 2015, Yani Iliev <notifications@github.com> wrote:

> The new version tries to skip gulp.src step but it doesn't have support
> for globbing yet. Is there a way to use gulp.src until globbing support is
> implemented?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sindresorhus/gulp-ruby-sass/issues/223>.
>


-- 
Rob Wierzbowski
@robwierzbowski <http://twitter.com/#!/robwierzbowski>
http://github.com/robwierzbowski
http://robwierzbowski.com

**Comment by yani-** [comment]
I have one css folder with 3 scss files in the root.
/scss
/scss/home.scss
/scss/about.scss
/scss/product.scss

There are multiple folders inside /scss that these 3 main files include common mixins from.

My previous task was defined like this:
```
gulp.task('css:build', function () {
‣   return gulp
‣   ‣   .src('lib/view/assets-development/css/*.scss')
‣   ‣   .pipe($.rubySass({
‣   ‣   ‣   style: 'expanded',
‣   ‣   ‣   precision: 10,
‣   ‣   ‣   loadPath: 'lib/view/assets-development/css'
‣   ‣   }))
‣   ‣   .on('error', console.error.bind(console))
‣   ‣   .pipe($.autoprefixer(AUTOPREFIXER_BROWSERS))
‣   ‣   .pipe($.csso())
‣   ‣   .pipe($.rename({suffix: '.min'}))
‣   ‣   .pipe(gulp.dest('lib/view/assets/css'))
‣   ‣   .pipe($.size({showFiles: true}));
});
```

**Comment by robwierzbowski** [comment]
With the latest version, you can use `sass.src('scss').pipe(gulp.dest('css'))` to process the entire directory, just like running `sass --update scss css` from the command line. 

From what I've seen, there are actually very few situations with Sass that need a file glob. The main issue right now is that incremental builds don't work yet, but I'm fixing that next.

Let me know if that works for you.

**Comment by robwierzbowski** [comment]
Glob sources are implemented in this PR: https://github.com/sindresorhus/gulp-ruby-sass/pull/251, if you would like to test.
