### ISSUE TITLE
Using gulp ruby sass as a dependency in Elastic Beanstalk.

### ISSUE THREAD

**Issue by JehandadK** [sindresorhus/gulp-ruby-sass#224]
I am using it in gulpfile as follows:

```js
.pipe($.changed('css', {extension: '.scss'}))
        .pipe($.changed('css', {extension: '.sass'}))
        .pipe($.rubySass({
            style: 'expanded',
            precision: 10,
            bundleExec: false
        }))
        .on('error', console.error.bind(console))

```
But the error is as follows despite being sass available on path

```
[12:03:22] Starting 'styles'...
{ [Error: spawn ENOENT: Missing the Sass executable. Please install and make available on your PATH.]
  message: 'spawn ENOENT: Missing the Sass executable. Please install and make available on your PATH.',
  showStack: false,
  showProperties: true,
  plugin: 'gulp-ruby-sass',
  __safety: { toString: [Function] } }
[12:03:22] 'css' all files 0 B
```

I have an open question as well

http://stackoverflow.com/questions/29895475/elastic-beanstalk-dependencies-not-available-in-npm-install/29937117#29937117

But whats important here is gulp-ruby-sass dosent work even if sass is installed in all ruby installations in elastic beanstalk I investigated the bundleExec option but that wasnt the case as well.

**Comment by robwierzbowski** [comment]
What happens when you run the sass gem directly from the command line? How does the OS know which versions of Ruby to use?

**Comment by JehandadK** [comment]
I ssh into the system and am installing the gem manually to locally install then use the it 
```
cd /var/app/current
sudo chmod 757 -R ./public-debug && sass --update client/css:public-debug/css --sourcemap=auto
```

**Comment by robwierzbowski** [comment]
Yes, looks fine. FYI, you don't have to explicitly set it to `false` since that is the default.

**Comment by robwierzbowski** [comment]
In your script you are starting with `$.changed(`. GRS is a source adapter — it's used instead of `gulp.src`, and can't have any functions called before it in the stream. 

Can you try again following the example in the readme, then re-open if the error persists.
