### ISSUE TITLE
InvalidOption: invalid option container

### ISSUE THREAD

**Issue by steoo** [sindresorhus/gulp-ruby-sass#225]
I'm running this task: 

`gulp.task('sass-ruby', function () {
    return ruby_sass('assets/sass', {
        style: options["style"] || "compressed",
        sourcemap: options["sourcemaps"] ? true : false
    })
        .pipe(gulpif(options["sourcemaps"], sourcemaps.write()))
        .pipe(gulp.dest('assets/css'));
});`

and it is giving me this error: 

`OptionParser::InvalidOption: invalid option: --container=gulp-ruby-sass`

Tried to `--trace` but it prints like 1 million line of code

Tried with a simpler task like

`gulp.task('sass-editor', function () {
    return ruby_sass('assets/sass/editor.scss')
        .on('error', function (err) {
            console.error('Error!', err.message);
        })
        .pipe(gulp.dest('assets/css'));
})`

and I get the same error. 

It used to work some day ago, any idea?

**Comment by robwierzbowski** [comment]
Ya, I think it's not being removed from the sass options anymore. Will take
a look and fix.

On Monday, May 11, 2015, Stefano <notifications@github.com> wrote:

> I'm running this task:
>
> gulp.task('sass-ruby', function () {
> return ruby_sass('assets/sass', {
> style: options["style"] || "compressed",
> sourcemap: options["sourcemaps"] ? true : false
> })
> .pipe(gulpif(options["sourcemaps"], sourcemaps.write()))
> .pipe(gulp.dest('assets/css'));
> });
>
> and it is giving me this error:
>
> OptionParser::InvalidOption: invalid option: --container=gulp-ruby-sass
>
> Tried to --trace but it prints like 1 million line of code
>
> Tried with a simpler task like
>
> gulp.task('sass-editor', function () {
> return ruby_sass('assets/sass/editor.scss')
> .on('error', function (err) {
> console.error('Error!', err.message);
> })
> .pipe(gulp.dest('assets/css'));
> })
>
> and I get the same error.
>
> It used to work some day ago, any idea?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sindresorhus/gulp-ruby-sass/issues/225>.
>


-- 
Rob Wierzbowski
@robwierzbowski <http://twitter.com/#!/robwierzbowski>
http://github.com/robwierzbowski
http://robwierzbowski.com

**Comment by steoo** [comment]
UP: this happens only in Windows, not on Linux. 
Windows: 
`sass -v`
`Sass 3.4.13 (Selective Steve)`

`"gulp-ruby-sass": "^1.0.5"`

Linux: 
`sass -v`
`Sass 3.4.13 (Selective Steve)`

`"gulp-ruby-sass": "^1.0.5"`

**Comment by robwierzbowski** [comment]
Very weird. Dargs should be removing that option here: https://github.com/sindresorhus/gulp-ruby-sass/blob/master/index.js#L68-L74.

Can you try this branch and see if it works? https://github.com/sindresorhus/gulp-ruby-sass/tree/rw/update-dargs

**Comment by robwierzbowski** [comment]
Closing for no response. Please re-open if it's still an issue!
