### ISSUE TITLE
another issue due to the lack of globbing

### ISSUE THREAD

**Issue by gruppjo** [sindresorhus/gulp-ruby-sass#226]
Hi, I'm also running into troubles because the `1.0.x` version doesn't support globbing. I've seen the issue  that @yani- created https://github.com/sindresorhus/gulp-ruby-sass/issues/223, but I cannot use the directory workaround. At least it has undesired side-effects in my case. I hope it's acceptable that I create another issue.

Here's why cannot use the directory approach. My project structure looks like this:
```
└──  app/           - your application folder
│   └──  bower_components/    - local installation of bower packages
│   └──  main/                - ---main module---
│   │   ├──  styles/main.scss         - scss styles
│   │   ├──  ... other stuff
│   └──  anotherModule/       - ---another  module---
│   │   ├──  styles/main.scss          - scss styles
│   │   ├──  ... other stuff
```

I used to glob all the `main.scss` files of the different modules. If I just use `sass('app/')` and let sass run over the whole directory, it will also search the `bower_components/` and compile all sass files there (and there's quite a few depending on the installed bower packages).

Any idea how to avoid this issue and are you planning on implementing globbing again?
Any help appreciated, thank you!

**Comment by robwierzbowski** [comment]
Why not put all of your styles into a single styles directory and run on `app/styles`? 

My priorities right now are to get this running *like* command line Sass, not differently. How would you manage your project if you were using command line Sass?

**Comment by gruppjo** [comment]
Ok, I understand that. It's kinda my fault for relying on it to work differently ;)

**Comment by robwierzbowski** [comment]
No worries!
