### ISSUE TITLE
Multiple instances of Sass tasks - confused to output files to required destination.

### ISSUE THREAD

**Issue by josephnvn** [sindresorhus/gulp-ruby-sass#228]
I have a strange scenario where my project is combination of sub projects. As a result I have to run the Sass compilations for files in different directories, compiled to different destinations. When running he tasks in loop in gulp, I noticed something strange. Depending on the compilation time for each sass the resultant files get copied into all directories or wrongs directories. 

When digged into code, I found that all files are compiled to temporary directory of node. Which I changed for my project to use the source directory to create a _temp directory and removed after copy.

CODE 

// sass options need unix style slashes
// tempDir = slash(path.join(osTempDir, options.container));
   tempDir = source.replace(/[^\/]*$/, '') + '/_temp';

Hope this helps!

**Comment by robwierzbowski** [comment]
Check out the `container` option.

**Comment by josephnvn** [comment]
Ah! How could I miss it :) nice one!

**Comment by robwierzbowski** [comment]
:+1:
