### ISSUE TITLE
task sass for *.sass files works but gulp.watch does not

### ISSUE THREAD

**Issue by joelremix** [sindresorhus/gulp-ruby-sass#229]
gulp sass task works correctly. It outputs css from .sass extension files

gulp watch task does not work but will work if source path is changed from *.sass to main.sass

I see a lot of working samples on the web that do this same thing except using .scss files.

<pre>

var paths = {
	//sass: 'app/acme/assets/sass/*main.sass', // will work with watch task
	sass: 'app/acme/assets/sass/*.sass',
};

gulp.task('sass', function()
{
	return sass(paths.sass,
		{
			style: 'expanded'
		})
		.pipe(gulp.dest('public/assets/css'));
});

</pre>

<pre>
gulp.task('watch', function()
{
	gulp.watch(paths.sass, ['sass']);

});
</pre>

The error I get is: 
Errno::ENOENT: No such file or directory - app/acme/assets/sass/*.sass

**Comment by kevva** [comment]
https://github.com/sindresorhus/gulp-ruby-sass/issues/200
