### ISSUE TITLE
Windows Temp Problem

### ISSUE THREAD

**Issue by DeezCashews** [sindresorhus/gulp-ruby-sass#230]
When trying to use gulp-ruby-sass I ran into a problem where my *.css files weren't being generated.  After an hour or two of debugging I finally realized the problem was with the command itself.  Slightly altering the command this is what doesn't work:
```bash
sass --style expanded --update C:/Users/DEVEL~1/AppData/Local/Temp/gulp-ruby-sass:output
```

This seems to be because of Windoze stupid short names because if I change the command to 
```bash
sass --style expanded --update C:/Users/developuser/AppData/Local/Temp/gulp-ruby-sass:output
```
it works just fine.  Anyone have any suggestions on how to workaround this for the time being besides using another user.  Besides that, is there anything that can be done from plugin side to support this (even though I'd agree its a PITA).

**Comment by UltCombo** [comment]
What happens if you quote the path argument?

```
sass --style expanded --update "C:/Users/DEVEL~1/AppData/Local/Temp/gulp-ruby-sass:output"
```

**Comment by DeezCashews** [comment]
Same thing, nothing happens because I assume ruby sass can't find C:/Users/DEVEL~1/Local/Temp/gulp-ruby-sass (since it's actually C:/Users/developuser/Local/....)

**Comment by DeezCashews** [comment]
The problem seems to lie with nodes `os.tmpdir()` which returns the C:/Users/DEVEL~1 (correctly as that is what also shows in my environment variables).  I did some experimenting using `path` and `fs` and Node.js seems to handle the ~1 Windows short names just fine, so I'm guessing it's a problem with sass/ruby.  If you think of a hack to add in the code it would be great, but I can't seem to find one right now.  

If anyone else runs into this, I just do the following to get by from my command prompt:

```bash
set TEMP=%USERPROFILE%\AppData\Local\Temp
```

This is the exact same definition as is set in my Environment Variables but setting it manually in the shell gives me the nice full path instead of the stupid short names.

**Comment by robwierzbowski** [comment]
Thanks for the great research! If you're relatively sure that it's a Sass
issue, can you submit an issue on the Sass tracker?

On Friday, June 12, 2015, DeezCashews <notifications@github.com> wrote:

> The problem seems to lie with nodes os.tmpdir() which returns the
> C:/Users/DEVEL~1 (correctly as that is what also shows in my environment
> variables). I did some experimenting using path and fs and Node.js seems
> to handle the ~1 Windows short names just fine, so I'm guessing it's a
> problem with sass/ruby. If you think of a hack to add in the code it would
> be great, but I can't seem to find one right now.
>
> If anyone else runs into this, I just do the following to get by from my
> command prompt:
>
> set TEMP=%USERPROFILE%\AppData\Local\Temp
>
> This is the exact same definition as is set in my Environment Variables
> but setting it manually in the shell gives me the nice full path instead of
> the stupid short names.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sindresorhus/gulp-ruby-sass/issues/230#issuecomment-111606950>
> .
>


-- 
Rob Wierzbowski
@robwierzbowski <http://twitter.com/#!/robwierzbowski>
http://github.com/robwierzbowski
http://robwierzbowski.com

**Comment by DeezCashews** [comment]
Sure, but I'm guessing they will simply roll their eyes as I often do and mutter "meh, windoze :/"  

p.s.  I also found that by changing my TEMP and TMP env variables to be `%USERPROFILE%\AppData\Local\Tmp` instead, Windows doesn't try to "help" by shortening the name (it must be looking specifically at AppData\Local\Temp because it seems to always know to shorten if it ends in that).

**Comment by robwierzbowski** [comment]
@DeezCashews Alright, just pushed and published a fix for your issue. [There's a new `tempDir` option](https://github.com/sindresorhus/gulp-ruby-sass#tempdir) that lets you assign your own temporary directory. Let me know if that works for you.

**Comment by robwierzbowski** [comment]
Looks like you fixed it in an alternate way without me, but now there's an option in plugin if others need it :).

**Comment by DeezCashews** [comment]
Solid @robwierzbowski  Nice to be able to compile to a .tmp directory in project anyways so you don't have to go poking around file system to see what was generated when debugging.  Nice little addition.

**Comment by robwierzbowski** [comment]
:raised_hands: :dancer: Sorry it took forever for me to get to this. Glad you like it!
