### ISSUE TITLE
Only compile some directories' sass files

### ISSUE THREAD

**Issue by ihaolin** [sindresorhus/gulp-ruby-sass#231]
Hello，I  am confused a bit about **gulp-ruby-sass**'s source files，I want to compile some directories' sass to custom some plugins' style，such as：

```javascript
var customScssPaths = [ 'plugins/wmgotop/*.scss', 'plugins/wmmark/*.scss' ];

// gulp task
gulp.src(customScssPaths)
        .pipe(sass({
            style: 'expanded',
            "sourcemap=none": true
        }))
        .pipe(autoprefixer('last 2 versions', 'safari 5', 'ie 8', 'ie 9', 'opera 12.1', 'ios 6', 'android 4'))
        .pipe(concat('women.css'))
        .pipe(gulp.dest('dist/css'))
        .pipe(concat('women.min.css'))
        .pipe(minifycss())
        .pipe(gulp.dest('dist/css'))
        .pipe(notify({message: 'styles completed!'}));
```
But this only generate **wmmark/*scss** 's css, not include  **wmgotop/*scss**，Should I do？

Thanks & Regards.

**Comment by robwierzbowski** [comment]
GRS takes arguments for source just like Sass does — for update (aka compiling a whole directory), you can only pass a single folder at a time (for example, `plugins/wmgotop`). Also, check out the code examples — GRS is a source adapter and is used instead of `gulp.src`.

**Comment by robwierzbowski** [comment]
Basically you use this plugin as you would use the Sass CLI itself. If the above explanation didn't help, please re-open.
