### ISSUE TITLE
Invalid US-ASCII character

### ISSUE THREAD

**Issue by designermonkey** [sindresorhus/gulp-ruby-sass#232]
Using version `0.7.1` and trying to output UTF-8` characters, I get this error message.

```
[15:01:07] { [Error: error /Users/designermonkey/Projects/Embark/dymo/dymopro-brand/german/sass/modules/colour-icons.scss (Line 43: Invalid US-ASCII character "\xC3")]
  message: 'error /Users/designermonkey/Projects/Embark/dymo/dymopro-brand/german/sass/modules/colour-icons.scss (Line 43: Invalid US-ASCII character "\\xC3")',
  showStack: false,
  showProperties: true,
  plugin: 'gulp-ruby-sass',
  __safety: { toString: [Function] } }
```

The file in question has `@charset 'UTF-8';` declared at the top and is saved in `UTF-8` encoding. It's imported into a `styles.scss` file which also has `@charset 'UTF-8';` at the top.

The character is `ß`.

The file processes fine using sass on the command line like so: `sass german/sass/styles.scss > test.css`.

I also dumped the command into the console and got:

```
sass [ '--no-cache',
  '--style',
  'compressed',
  '--update',
  '/var/folders/s5/pxf9hj954kq1fxt6ctzbkdc40000gn/T/gulp-ruby-sass:/var/folders/s5/pxf9hj954kq1fxt6ctzbkdc40000gn/T/gulp-ruby-sass/_14139e58-9ebe-4c0f-beca-73a65bb01ce9',
  '--load-path',
  'german/sass' ]
```

So I ran that manually on the command line too, and it worked fine. I'm at a loss as to what's causing this.

**Comment by robwierzbowski** [comment]
That is confusing. Can you:

- try with the latest release?
- try with no other gulp tasks?

**Comment by designermonkey** [comment]
according to github, it is the latest release?

https://github.com/sindresorhus/gulp-ruby-sass/releases

**Comment by UltCombo** [comment]
1.0.5 is the latest released npm package version: https://www.npmjs.org/package/gulp-ruby-sass

**Comment by UltCombo** [comment]
You will also need to read the [README](https://github.com/sindresorhus/gulp-ruby-sass#important) in order to migrate < 1.0.0 code to 1.0.0+.

**Comment by arthurvr** [comment]
> according to github, it is the latest release?

We generally don't do real GitHub release just a tag. https://github.com/sindresorhus/gulp-ruby-sass/tags

**Comment by robwierzbowski** [comment]
Maybe we should. I've been lazy :P

**Comment by askobara** [comment]
@designermonkey, try to run gulp like this:
`LC_CTYPE=en_US.UTF-8 gulp <your_target>`

I had similar problem and I fixed it so

**Comment by robwierzbowski** [comment]
Going to close this as it's against an outdated version of the plugin. Please open if you have the same problem on the most recent version (according to npm).
