### ISSUE TITLE
Issue with trailing slash on windows

### ISSUE THREAD

**Issue by ihorml** [sindresorhus/gulp-ruby-sass#234]
Please fix the issue with trailing slash on doing gulp.dest:

It doesn't work:
```
.pipe(gulp.dest(options.tmp + '/serve/app/'))
```

It works:

```
.pipe(gulp.dest(options.tmp + '/serve/app'))
```

**Comment by robwierzbowski** [comment]
This is an issue with gulp itself, not with this plugin in particular. gulp provides the `gulp.dest` function.
