### ISSUE TITLE
File to import not found or unreadable

### ISSUE THREAD

**Issue by blackjackcf** [sindresorhus/gulp-ruby-sass#238]
Hey all,

Attempting to move away from the Rails asset pipeline and rolling assets with Gulp instead. Got JS working just fine, but having a lot of trouble with Sass. For some reason, gulp-ruby-sass errors out when attempting to read @imports. I've already seen the related issues that are similar to https://github.com/sindresorhus/gulp-ruby-sass/issues/148 and I'm not using gulp.src. 

My gulpfile.coffee looks like this:

```
gulp.task 'styles', tasks.styles = ->
  sass('app/assets/stylesheets/application.css.sass',
    {
      verbose: true
      loadPath: [
        "app/assets/stylesheets/shared",
        "app/assets/stylesheets"
        ]
    })
    .on 'error', (err) ->
      console.error 'Error', err.message
    .pipe(concat 'app.css')
    .pipe(size())
    .pipe(gulp.dest publicPath)
    .pipe(minifyCSS())
    .pipe(rename({extname: "min.css"}))
    .pipe(size())
    .pipe(gulp.dest publicPath+'/stylesheets')
```

My application.css.sass file looks like this: 

```
@import 'fonts'
@import 'bootstrap-datepicker3'
@import 'jquery.mmenu.all'
@import 'jquery.ui'
...
```

It runs into the @import 'fonts' and throw the following error:

```
error app/assets/stylesheets/application.css.sass (Line 4: File to import not found or unreadable: fonts.
```

Is there something I'm missing?

**Comment by robwierzbowski** [comment]
Can you run gulp sass -v and check the actual Sass command being run? If you run that command, what's your Sass output?

I'm guessing there's some relative path issues here. Where is `fonts.sass` in your project? Is it called `fonts.sass` or `fonts.css.sass`? Sass only strips the Sass extension IIRC, different from working with the asset pipeline.

**Comment by iRet** [comment]
+1 same for me:

Getting: `(Line 1: File to import not found or unreadable: redactor/redactor.`
Using: `sass('./app/assets/stylesheets', loadPath: './vendor/assets/javascripts/')`

However vendor/assets/javascripts contains redactor/redactor.css

**Comment by robwierzbowski** [comment]
Testing now, this looks like a problem with loadpaths. Not sure why yet; it seems like the loadpaths are correct in the error message.

**Comment by robwierzbowski** [comment]
OK, the above was my user error. Things seem to be working fine with imports and loadpaths for me. 

When I have the function:
```js
return sass('source/fixture-a.scss', { loadPath: './source/component', verbose: true })
``` 

with the stylesheet `fixture-a.scss`
```scss
@import 'obj-2';

body {
  @include baz();
}
```

and the file `_.obj-2.scss` in the directory `source/components/`,
and run it with `gulp sass -v`, I get the output:
```
Running command sass --sourcemap=none --load-path=./source/component source/fixture-a.scss /var/folders/7b/lvtjddtn5cd7wrfszwtz141r0000gn/T/gulp-ruby-sass/fixture-a.css
```

and everything completes as expected. Can you show me how your setup differs from this?

BTW I'm on OSX Yosemite.

**Comment by robwierzbowski** [comment]
If one of you can create a repo with a reduced test case it would help me debug. Your project with everything removed but the package/bower.json files, the gulp task, and one failing import.

**Comment by blackjackcf** [comment]
@robwierzbowski - I got mine resolved. Looks like it's because I was using the deprecated 'css.sass' extension as opposed to just '.sass.' When I changed it over, it worked like a charm.

**Comment by robwierzbowski** [comment]
@blackjackcf :raised_hands: Nice!

@iRet, are you still experiencing issues?

**Comment by iRet** [comment]
@blackjackcf thanks for reply! 
I've temporary whitched to a different ticket. I will check it again in a day or two. As for file extension, yep, same issue in my app (css.sass) and I've already get it, but it seems like this particular (with redactor) is unrelated because vendor assets in usual css. I'll drop a line.

**Comment by iRet** [comment]
@blackjackcf my problems was in folders in import call.
`@import 'redactor/redactor';`
When I leved just filename it passes.
That's weird because same gem but using sprockets renders this file well.
Anyway it seems like not gulp-ruby-sass issue, it builds right commandline string.
Thanks for help!

**Comment by robwierzbowski** [comment]
Sounds like everyone has resolved their issues! Closing.
