### ISSUE TITLE
Can not import Partials into a Base File SCSS

### ISSUE THREAD

**Issue by prio101** [sindresorhus/gulp-ruby-sass#241]
I am trying to get the partials in a base file . And then I tried to get it on the gulp . But it is not working.
here is the code 

```js
var gulp        = require('gulp');
var rubyGulp    = require('gulp-ruby-sass');

gulp.task('sass',function(){
    return rubyGulp('bower_components/bootstrap-sass/assets/stylesheets/bootstrap/_bootstrap.scss').on('error',function(err){
        console.error('Error!!',err.message);
    }).pipe(gulp.dest('public/css/'));
});


gulp.task('default',['sass']);
```

**Comment by robwierzbowski** [comment]
It looks like you are compiling a partial alone; Sass does not output files
that start with an '_'. Try renaming _bootstrap.scss to bootstrap.scss, or
importing it into a file called main.scss or something similar and
compiling that file.

On Tuesday, August 11, 2015, Prio <notifications@github.com> wrote:

> I am trying to get the partials in a base file . And then I tried to get
> it on the gulp . But it is not working.
> here is the code
>
> `js
> var gulp = require('gulp');
> var rubyGulp = require('gulp-ruby-sass');
>
> gulp.task('sass',function(){
> return
> rubyGulp('bower_components/bootstrap-sass/assets/stylesheets/bootstrap/_bootstrap.scss').on('error',function(err){
> console.error('Error!!',err.message);
> }).pipe(gulp.dest('public/css/'));
> });
>
> gulp.task('default',['sass']);`
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sindresorhus/gulp-ruby-sass/issues/241>.
>


-- 
Rob Wierzbowski
@robwierzbowski <http://twitter.com/#!/robwierzbowski>
http://github.com/robwierzbowski
http://robwierzbowski.com

**Comment by prio101** [comment]
@robwierzbowski  You are pretty wrong . I am compiling a base partial . which includes a hell of a list of small partials . And I am back here to close the issue because I solved the problem .

**Comment by robwierzbowski** [comment]
Out of curiosity, what was the solution? If you share it others with the
same issue can benefit from it.

On Tuesday, August 11, 2015, Prio <notifications@github.com> wrote:

> Closed #241 <https://github.com/sindresorhus/gulp-ruby-sass/issues/241>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sindresorhus/gulp-ruby-sass/issues/241#event-379069192>
> .
>


-- 
Rob Wierzbowski
@robwierzbowski <http://twitter.com/#!/robwierzbowski>
http://github.com/robwierzbowski
http://robwierzbowski.com

**Comment by prio101** [comment]
Well, Actually this will prove how much fool and idiot I am . Okay . I was working with the Laravel 5.1 . I tried to download Bootstrap-sass with bower. And then Compile it with GULP . I made  a horrible mistake by putting the src path wrong . Sorry . But yeah , it compiled a base partial with _prefix

**Comment by robwierzbowski** [comment]
Ha, no worries. I guess if you specify the base file it compiles it no
matter what; directory compiling ignores partials. Good to know.

On Tuesday, August 11, 2015, Prio <notifications@github.com> wrote:

> Well, Actually this will prove how much fool and idiot I am . Okay . I was
> working with the Laravel 5.1 . I tried to download Bootstrap-sass with
> bower. And then Compile it with GULP . I made a horrible mistake by putting
> the src path wrong . Sorry . But yeah , it compiled a base partial with
> _prefix
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sindresorhus/gulp-ruby-sass/issues/241#issuecomment-129855005>
> .
>


-- 
Rob Wierzbowski
@robwierzbowski <http://twitter.com/#!/robwierzbowski>
http://github.com/robwierzbowski
http://robwierzbowski.com
