### ISSUE TITLE
Not be able to compile scss file 'typeerror arguments to path.join must be strings'

### ISSUE THREAD

**Issue by shahjehanali1** [sindresorhus/gulp-ruby-sass#248]
Hi,
Please Help Me, I'm Trying to compile my scss by using gulp-ruby-sass

Its give me following errors 
![image](https://cloud.githubusercontent.com/assets/8455072/9459551/4e143a5c-4b16-11e5-932f-8df4d9988bb3.png)

this is my gulpfile.js code

![image](https://cloud.githubusercontent.com/assets/8455072/9459572/96634c44-4b16-11e5-95f6-eac108c1dff0.png)

gulp.task('styles', function() {
	gulp.src('scss/new-style.scss')
	.pipe(sass())
	.pipe(gulp.dest('css/compile'));
});

**Comment by shahjehanali1** [comment]
please help me??????????????????????????????????

**Comment by robwierzbowski** [comment]
Please read the readme for examples of how to set up the task or search
closed issues on github for your error. You'll find what you need :)

Rob

On Tuesday, August 25, 2015, shahjehanali1 <notifications@github.com> wrote:

> please help me??????????????????????????????????
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sindresorhus/gulp-ruby-sass/issues/248#issuecomment-134553398>
> .
>


-- 
Rob Wierzbowski
@robwierzbowski <http://twitter.com/#!/robwierzbowski>
http://github.com/robwierzbowski
http://robwierzbowski.com

**Comment by robwierzbowski** [comment]
Specifically note that gulp-ruby-sass is a *source adapter* and is used in place of `gulp.src`.

https://github.com/sindresorhus/gulp-ruby-sass#usage
https://github.com/sindresorhus/gulp-ruby-sass/issues?utf8=%E2%9C%93&q=is%3Aissue+arguments+to+path.join+must+be+strings
