### ISSUE TITLE
Sourcemaps created, but browser is not reading

### ISSUE THREAD

**Issue by smlombardi** [sindresorhus/gulp-ruby-sass#255]
I am using these 2 tandem tasks: 

````
// process scss to sass, inject changes
gulp.task('sass', function() {
  var cssfilter = filter('*.css', {restore:true});
  return sass('./app/assets/sass', {
      style: 'condensed',
      sourcemaps: false
    })
    .on('error', function(err) {
      console.error('Error!', err.message);
    })
    .pipe(gulp.dest('./app/assets/css'))
    .pipe(cssfilter)
    .pipe(reload({
      stream: true
    }));
});


// kick off css processing with maps
gulp.task('css-working', ['sass'], function() {
  return gulp.src('./app/assets/css/*.css')
    .pipe(sourcemaps.init())
    .pipe(postcss([autoprefixer({
      browsers: ['last 2 versions']
    })]))
    .pipe(sourcemaps.write('.'))
    .pipe(gulp.dest('./app/assets/css/'));
});
````

Everything works, `.map` files are generated alongside the css, BUT chrome is not seeing the css source, just the regular css.

**Comment by robwierzbowski** [comment]
Which version of the plugin are you using, and what does your final
directory structure look like (specifically CSS, maps, and the directory
you're serving from). Can you also open up a CSS file and copy the map file
comment?

On Tuesday, September 1, 2015, Steve Lombardi <notifications@github.com>
wrote:

> I am using these 2 tandem tasks:
>
> // process scss to sass, inject changes
> gulp.task('sass', function() {
>   var cssfilter = filter('*.css', {restore:true});
>   return sass('./app/assets/sass', {
>       style: 'condensed',
>       sourcemaps: false
>     })
>     .on('error', function(err) {
>       console.error('Error!', err.message);
>     })
>     .pipe(gulp.dest('./app/assets/css'))
>     .pipe(cssfilter)
>     .pipe(reload({
>       stream: true
>     }));
> });
>
>
> // kick off css processing with maps
> gulp.task('css-working', ['sass'], function() {
>   return gulp.src('./app/assets/css/*.css')
>     .pipe(sourcemaps.init())
>     .pipe(postcss([autoprefixer({
>       browsers: ['last 2 versions']
>     })]))
>     .pipe(sourcemaps.write('.'))
>     .pipe(gulp.dest('./app/assets/css/'));
> });
>
> Everything works, .map files are generated alongside the css, BUT chrome
> is not seeing the css source, just the regular css.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sindresorhus/gulp-ruby-sass/issues/255>.
>


-- 
Rob Wierzbowski
@robwierzbowski <http://twitter.com/#!/robwierzbowski>
http://github.com/robwierzbowski
http://robwierzbowski.com

**Comment by smlombardi** [comment]
In the interim I have updated the main components, gulp-ruby-sass 1.4, gulp-sourcemaps 1.5.2, autoprefixer-core 5.2.1, gulp 3.9.0.  Now I run it, everything is generated BUT now there is no longer a comment at the bottom of the css files.  With the original versions of the components, it was `SourcemappingURL=documentation.css.map`

My directory structure is 
````
app
|
--assets
    |
    -- css
    -- sass
    -- images
````

**Comment by robwierzbowski** [comment]
OK. Can you make a reduced test case using only the gulp-ruby-sass plugin? Something like:

```js
gulp.task('sass', function() {
  return sass('./app/assets/sass', {
      style: 'condensed',
      sourcemaps: true // <- I noticed you turned sourcemaps off in you example. If you want sourcemaps, they need to be on :)
    })
    .on('error', function(err) {
      console.error('Error!', err.message);
    })
    .pipe(gulp.dest('./app/assets/css'))
});
```

**Comment by smlombardi** [comment]
Did a test case, as you asked:
````
gulp.task('sass', function() {
  return sass('./app/assets/sass', {sourcemap: true})
    .on('error', sass.logError)

    // For inline sourcemaps
    .pipe(sourcemaps.write())

    // For file sourcemaps
    .pipe(sourcemaps.write('maps', {
      includeContent: false,
      sourceRoot: 'source'
    }))

    .pipe(gulp.dest('./app/assets/css'));
});
````

This created map files in `/assets/css/maps` AND injected the whole map into the CSS file (not what I expected or wanted), a huge block beginning with `/*# sourceMappingURL=data:application/json;base64,`

it also added a slug as the last line:
`/*# sourceMappingURL=maps/documentation.css.map */`

What's going on?

**Comment by robwierzbowski** [comment]
That's what you asked it to do. You've included both the inline sourcemaps example and the file sourcemaps example.

```
    // For inline sourcemaps <-------------
    .pipe(sourcemaps.write())

    // For file sourcemaps <-------------
    .pipe(sourcemaps.write('maps', {
      includeContent: false,
      sourceRoot: 'source'
    }))
```

Choose whichever one you want (may want to read the gulp-sourcemaps docs to get a better idea of what each one is good for) and only include that example. Note for file sourcemaps you'll have to set the gulp-sourcemap options to the correct values for your project.

**Comment by smlombardi** [comment]
I also noticed that the map references do not show in dev tools initially; I often need to reload the browser at least once to see the SCSS references.  Any idea why?

Also, now I need to integrate Autoprefixer into this without breaking it.  Any recommendations?

**Comment by robwierzbowski** [comment]
1. Sounds like an issue with when you're using livereload or browsersync or what not to reoad the browser. Can't really debug from this end.

2. You should be able to add it to the stream with no further issues.

**Comment by smlombardi** [comment]
thanks

**Comment by robwierzbowski** [comment]
No problem.

**Comment by smlombardi** [comment]
Reopening only to post the final task, if case people are Googling for this issue like I was:

`````
gulp.task('sass', function() {
  var cssfilter = filter('*.css', {restore:true});
  return sass('./app/assets/sass', {sourcemap: true})
    .on('error', sass.logError)

    // For inline sourcemaps
    // .pipe(sourcemaps.write())

    .pipe(postcss([autoprefixer({
      browsers: ['last 2 versions']
    })]))

    // For file sourcemaps
    .pipe(sourcemaps.write('maps', {
      includeContent: false,
      sourceRoot: 'source'
    }))

    .pipe(gulp.dest('./app/assets/css'))

    .pipe(cssfilter)

    .pipe(browserSync.stream());
});
````
