### ISSUE TITLE
Don't work windows7

### ISSUE THREAD

**Issue by utz0r2** [sindresorhus/gulp-ruby-sass#256]
![Image of Yaktocat](http://veselov.sumy.ua/sub/gyazo/i/019020a0f33d8eff0c5ceca48060.png)
```
'use strict';
var gulp = require('gulp');
var sass = require('gulp-ruby-sass');
var sourcemaps = require('gulp-sourcemaps');

gulp.task('sass', function() {
	return sass('source', { verbose: true })
	.on('error', sass.logError)
	.pipe(sourcemaps.write())
	.pipe(gulp.dest('result'));
});
```
example from repository

**Comment by robwierzbowski** [comment]
What doesn't work? Are there no output files, or are the output files
corrupted? Is it just the logging? I need more information.

On Sunday, September 6, 2015, utz0r2 <notifications@github.com> wrote:

> [image: Image of Yaktocat]
> <https://camo.githubusercontent.com/fc8a181d09ae1ef3575c16b246ff6970a2e27ba3/687474703a2f2f766573656c6f762e73756d792e75612f7375622f6779617a6f2f692f303139303230613066333364386566663063356365636134383036302e706e67>
>
> 'use strict';
> var gulp = require('gulp');
> var sass = require('gulp-ruby-sass');
> var sourcemaps = require('gulp-sourcemaps');
>
> gulp.task('sass', function() {
>     return sass('source', { verbose: true })
>     .on('error', sass.logError)
>     .pipe(sourcemaps.write())
>     .pipe(gulp.dest('result'));
> });
>
> example from repository
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sindresorhus/gulp-ruby-sass/issues/256>.
>


-- 
Rob Wierzbowski
@robwierzbowski <http://twitter.com/#!/robwierzbowski>
http://github.com/robwierzbowski
http://robwierzbowski.com

**Comment by utz0r2** [comment]
No output files. Wrote finished but not to did.

**Comment by robwierzbowski** [comment]
Thanks. Can you tell me the version of gulp-ruby-sass you're using? Does
the previous version work?

Rob Wierzbowski
@robwierzbowski <http://twitter.com/#!/robwierzbowski>
http://github.com/robwierzbowski
http://robwierzbowski.com

**Comment by utz0r2** [comment]
node v0.12.7
gulp CLI version 3.9.0
gulp Local version 3.9.0
gulp-ruby-sass	1.4.0

1.3.0 - don't work, behavior is the same
1.2.0 - don't work but show error
![Image of veselov.sumy.ua](http://veselov.sumy.ua/sub/gyazo/i/838cdbd0bca4b6dfe957202d443a.png)

**Comment by robwierzbowski** [comment]
Thanks, that helps. Does 1.1 work?

Rob Wierzbowski
@robwierzbowski <http://twitter.com/#!/robwierzbowski>
http://github.com/robwierzbowski
http://robwierzbowski.com

**Comment by utz0r2** [comment]
don't work like 1.2.0
i add to index.js in block stderr
```
	sass.stderr.on('data', function (data) {
		console.log(' stream :=>>> ' + JSON.stringify(stream) );
		console.log(' intermediateDir :=>>> ' + intermediateDir );
		console.log(' data :=>>> ' + data );
		logger.stderr(stream, intermediateDir, data);
	});
````
and get
![Image of veselov.sumy.ua](http://veselov.sumy.ua/sub/gyazo/i/7e73fdc1ecfff02690f61fed124b.png)
temp directory is empty and data return text in incomprehensible encoding from parameter data

maybe this information will helpful

**Comment by robwierzbowski** [comment]
Thanks, that's great information. I'll look into it.

Can you compile Sass with the Sass gem by itself?

Rob Wierzbowski
@robwierzbowski <http://twitter.com/#!/robwierzbowski>
http://github.com/robwierzbowski
http://robwierzbowski.com

**Comment by utz0r2** [comment]
Solved
Work! Problem was with ruby (reinstall in new dir). Thanks  @robwierzbowski

**Comment by robwierzbowski** [comment]
Glad you figured it out :+1: :+1: :+1:
