### ISSUE TITLE
gulp-ruby-sass compiling to wrong directory

### ISSUE THREAD

**Issue by jessepinuelas** [sindresorhus/gulp-ruby-sass#258]
On windows my sass files are being compiled to C:/Users/Username/AppData/Local/Temp/gulp-ruby-sass... They never make there way to my tmp directory within my project. No css file ever gets compiled. I am not having this issue on Mac OSX. Any idea why this would happen on Windows when using gulp-ruby-sass? Am I missing some sort of configuration/step on Windows?

**Comment by robwierzbowski** [comment]
Please post your task, try without any other plugins (a reduced test case),
and make sure Sass works from the command line in windows. There aren't any
extra setup steps but there are so many moving pieces here it can get kind
of tricky.

On Tuesday, September 8, 2015, Jesse Pinuelas <notifications@github.com>
wrote:

> On windows my sass files are being compiled to
> C:/Users/Username/AppData/Local/Temp/gulp-ruby-sass... They never make
> there way to my tmp directory within my project. No css file ever gets
> compiled. I am not having this issue on Mac OSX. Any idea why this would
> happen on Windows when using gulp-ruby-sass? Am I missing some sort of
> configuration/step on Windows?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sindresorhus/gulp-ruby-sass/issues/258>.
>


-- 
Rob Wierzbowski
@robwierzbowski <http://twitter.com/#!/robwierzbowski>
http://github.com/robwierzbowski
http://robwierzbowski.com

**Comment by jessepinuelas** [comment]
Verified sass is working from Windows command line by running a simple watch.

Task
gulp > styles

'use strict';

var path = require('path');
var gulp = require('gulp');
var conf = require('./conf');

var browserSync = require('browser-sync');

var $ = require('gulp-load-plugins')();

var wiredep = require('wiredep').stream;
var _ = require('lodash');

gulp.task('styles', function () {
  var sassOptions = {
    style: 'expanded'
  };

  var injectFiles = gulp.src([
    path.join(conf.paths.src, '/app/**/*.scss'),
    path.join('!' + conf.paths.src, '/app/index.scss')
  ], { read: false });

  var injectOptions = {
    transform: function(filePath) {
      filePath = filePath.replace(conf.paths.src + '/app/', '');
      return '@import "' + filePath + '";';
    },
    starttag: '// injector',
    endtag: '// endinjector',
    addRootSlash: false
  };

  var cssFilter = $.filter('**/*.css');

  return gulp.src([
    path.join(conf.paths.src, '/app/index.scss')
  ])
    .pipe($.inject(injectFiles, injectOptions))
    .pipe(wiredep(_.extend({}, conf.wiredep)))
    .pipe($.rubySass(sassOptions)).on('error', conf.errorHandler('RubySass'))
    .pipe(cssFilter)
    .pipe($.sourcemaps.init({ loadMaps: true }))
    .pipe($.autoprefixer()).on('error', conf.errorHandler('Autoprefixer'))
    .pipe($.sourcemaps.write())
    .pipe(cssFilter.restore())
    .pipe(gulp.dest(path.join(conf.paths.tmp, '/serve/app/')))
    .pipe(browserSync.reload({ stream: true }));
});

**Comment by robwierzbowski** [comment]
GRS is a source adapter. Use it instead of gulp.src. See the docs for
examples.

On Tuesday, September 8, 2015, Jesse Pinuelas <notifications@github.com>
wrote:

> Verified sass is working from Windows command line by running a simple
> watch.
>
> Task
> gulp > styles
>
> 'use strict';
>
> var path = require('path');
> var gulp = require('gulp');
> var conf = require('./conf');
>
> var browserSync = require('browser-sync');
>
> var $ = require('gulp-load-plugins')();
>
> var wiredep = require('wiredep').stream;
> var _ = require('lodash');
>
> gulp.task('styles', function () {
> var sassOptions = {
> style: 'expanded'
> };
>
> var injectFiles = gulp.src([
> path.join(conf.paths.src, '/app/**/*.scss'),
> path.join('!' + conf.paths.src, '/app/index.scss')
> ], { read: false });
>
> var injectOptions = {
> transform: function(filePath) {
> filePath = filePath.replace(conf.paths.src + '/app/', '');
> return '@import <https://github.com/import> "' + filePath + '";';
> },
> starttag: '// injector',
> endtag: '// endinjector',
> addRootSlash: false
> };
>
> var cssFilter = $.filter('**/*.css');
>
> return gulp.src([
> path.join(conf.paths.src, '/app/index.scss')
> ])
> .pipe($.inject(injectFiles, injectOptions))
> .pipe(wiredep(_.extend({}, conf.wiredep)))
> .pipe($.rubySass(sassOptions)).on('error', conf.errorHandler('RubySass'))
> .pipe(cssFilter)
> .pipe($.sourcemaps.init({ loadMaps: true }))
> .pipe($.autoprefixer()).on('error', conf.errorHandler('Autoprefixer'))
> .pipe($.sourcemaps.write())
> .pipe(cssFilter.restore())
> .pipe(gulp.dest(path.join(conf.paths.tmp, '/serve/app/')))
> .pipe(browserSync.reload({ stream: true }));
> });
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sindresorhus/gulp-ruby-sass/issues/258#issuecomment-138706042>
> .
>


-- 
Rob Wierzbowski
@robwierzbowski <http://twitter.com/#!/robwierzbowski>
http://github.com/robwierzbowski
http://robwierzbowski.com

**Comment by sunshinecotejo** [comment]
Hi, 

I have the issue.

`D:\Dev\NRI\neap\neap-frontend>gulp
[22:03:31] Using gulpfile D:\Dev\NRI\neap\neap-frontend\gulpfile.js
[22:03:31] Starting 'clean'...
[22:03:31] Finished 'clean' after 90 ms
[22:03:31] Starting 'default'...
[22:03:31] Starting 'scripts'...
[22:03:31] Starting 'styles'...
[22:03:32] Starting 'partials'...
[22:03:32] Starting 'fonts'...
[22:03:33] Starting 'other'...
[22:03:33] Starting 'images'...
[22:03:33] Finished 'default' after 1.52 s
[22:03:33] gulp-inject 1 files into app.scss.
[22:03:34] gulp-ruby-sass: directory ../../../../../sunshine.cotejo/AppData/Loca
l/Temp/gulp-ruby-sass
[22:03:34] Finished 'other' after 1.78 s
[22:03:34] Finished 'partials' after 2.35 s
[22:03:36] Finished 'fonts' after 3.82 s
[22:03:37] Time: 4833ms
        Asset     Size  Chunks             Chunk Names
app.module.js  24.5 kB       0  [emitted]  main
[22:03:37] Finished 'scripts' after 6.47 s
[22:03:38] Finished 'images' after 4.99 s
[22:03:41] gulp-ruby-sass: write ../../../../../sunshine.cotejo/AppData/Local/Te
mp/gulp-ruby-sass/app.css
      write ../../../../../sunshine.cotejo/AppData/Local/Temp/gulp-ruby-sass/app
.css.map
[22:03:41] Finished 'styles' after 9.39 s
[22:03:41] Starting 'inject'...
[22:03:41] gulp-inject Nothing to inject into index.html.
[22:03:41] gulp-inject 1 files into index.html.
[22:03:41] Finished 'inject' after 56 ms
[22:03:41] Starting 'html'...
[22:03:41] gulp-inject 1 files into index.html.
[22:03:42] dist\ maps\scripts\app-acf08d7a16.js.map 44.16 kB
[22:03:43] dist\ maps\styles\vendor-5f4f50ddc1.css.map 94.16 kB
[22:03:53] dist\ maps\scripts\vendor-e099ef808c.js.map 5.22 MB
[22:03:53] dist\ scripts\app-acf08d7a16.js 15.6 kB
[22:03:53] dist\ styles\vendor-5f4f50ddc1.css 226 kB
[22:03:53] dist\ scripts\vendor-e099ef808c.js 1.03 MB
[22:03:53] dist\ index.html 770 B
[22:03:53] dist\ all files 6.64 MB
[22:03:53] Finished 'html' after 12 s
[22:03:53] Starting 'build'...
[22:03:53] Finished 'build' after 5.99 µs
`

'use strict';

var path = require('path');
var gulp = require('gulp');
var conf = require('./conf');

var $ = require('gulp-load-plugins')({
    pattern: ['gulp-*', 'main-bower-files', 'uglify-save-license', 'del']
});

gulp.task('partials', function () {
    return gulp.src([
        path.join(conf.paths.src, '/app/**/**/*.html'),
        path.join(conf.paths.tmp, '/serve/app/**/*.html')
    ])
    .pipe($.minifyHtml({
        empty: true,
        spare: true,
        quotes: true
    }))
    .pipe($.angularTemplatecache('templateCacheHtml.js', {
        module: 'rakan',
        root: 'app'
    }))
    .pipe(gulp.dest(conf.paths.tmp + '/partials/'));
});

gulp.task('html', ['inject', 'partials'], function () {
    var partialsInjectFile = gulp.src(path.join(conf.paths.tmp, '/partials/templateCacheHtml.js'), { read: false });
    var partialsInjectOptions = {
        starttag: '',
        ignorePath: path.join(conf.paths.tmp, '/partials'),
        addRootSlash: false
    };

    var htmlFilter = $.filter('*.html', { restore: true });
    var jsFilter = $.filter('**/*.js', { restore: true });
    var cssFilter = $.filter('**/*.css', { restore: true });
    var assets;

    return gulp.src(path.join(conf.paths.tmp, '/serve/*.html'))
        .pipe($.inject(partialsInjectFile, partialsInjectOptions))
        .pipe(assets = $.useref.assets())
        .pipe($.rev())
        .pipe(jsFilter)
        .pipe($.sourcemaps.init())
        .pipe($.uglify({ preserveComments: $.uglifySaveLicense })).on('error', conf.errorHandler('Uglify'))
        .pipe($.sourcemaps.write('maps'))
        .pipe(jsFilter.restore)
        .pipe(cssFilter)
        .pipe($.sourcemaps.init())
        .pipe($.minifyCss({ processImport: false }))
        .pipe($.sourcemaps.write('maps'))
        .pipe(cssFilter.restore)
        .pipe(assets.restore())
        .pipe($.useref())
        .pipe($.revReplace())
        .pipe(htmlFilter)
        .pipe($.minifyHtml({
            empty: true,
            spare: true,
            quotes: true,
            conditionals: true
        }))
        .pipe(htmlFilter.restore)
        .pipe(gulp.dest(path.join(conf.paths.dist, '/')))
        .pipe($.size({ title: path.join(conf.paths.dist, '/'), showFiles: true }));
  });

// Only applies for fonts from bower dependencies
// Custom fonts are handled by the "other" task
gulp.task('fonts', function () {
    return gulp.src($.mainBowerFiles())
        .pipe($.filter('**/*.{eot,svg,ttf,woff,woff2}'))
        .pipe($.flatten())
        .pipe(gulp.dest(path.join(conf.paths.dist, '/fonts/')));
});

gulp.task('images', function () {
    return gulp.src(path.join(conf.paths.src, '/assets/img/**/*'))
    .pipe(gulp.dest(path.join(conf.paths.dist, '/assets/img/')));
});

gulp.task('other', function () {
    var fileFilter = $.filter(function (file) {
        return file.stat.isFile();
    });

    return gulp.src([
        path.join(conf.paths.src, '/app/**/*'),
        path.join('!' + conf.paths.src, '/**/*.{html,css,js,scss,ts,md}')
    ])
    .pipe(fileFilter)
    .pipe(gulp.dest(path.join(conf.paths.dist, '/app/')));
});

gulp.task('clean', function () {
    return $.del([path.join(conf.paths.dist, '/'), path.join(conf.paths.tmp, '/partials'), path.join(conf.paths.tmp, '/serve')]);
});

gulp.task('build', ['html', 'fonts', 'other', 'images']);
