### ISSUE TITLE
node dependencies error with utils

### ISSUE THREAD

**Issue by froucher** [sindresorhus/gulp-ruby-sass#262]
With the last update to version 2.0.0, it is not working node dependencies:

```
Error: Cannot find module './utils'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/home/bamboo/bamboo-agent-home/xml-data/build-dir/BRES-MB0-BCP/workspace/node_modules/gulp-ruby-sass/logger.js:3:15)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
```
Please add this dependency to package.json.

**Comment by robwierzbowski** [comment]
You're right, I forgot to add that file to the package.json files array.
Tests were passing because it's a clone of the repo, not installed by npm.

Will fix in 30 min and push a new release.

On Thursday, September 10, 2015, Felipe <notifications@github.com> wrote:

> With the last update to version 2.0.0, it is not working node dependencies:
>
> Error: Cannot find module './utils'
>     at Function.Module._resolveFilename (module.js:338:15)
>     at Function.Module._load (module.js:280:25)
>     at Module.require (module.js:364:17)
>     at require (module.js:380:17)
>     at Object.<anonymous> (/home/bamboo/bamboo-agent-home/xml-data/build-dir/BRES-MB0-BCP/workspace/node_modules/gulp-ruby-sass/logger.js:3:15)
>     at Module._compile (module.js:456:26)
>     at Object.Module._extensions..js (module.js:474:10)
>     at Module.load (module.js:356:32)
>     at Function.Module._load (module.js:312:12)
>     at Module.require (module.js:364:17)
>
> Please add this dependency to package.json.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sindresorhus/gulp-ruby-sass/issues/262>.
>


-- 
Rob Wierzbowski
@robwierzbowski <http://twitter.com/#!/robwierzbowski>
http://github.com/robwierzbowski
http://robwierzbowski.com

**Comment by robwierzbowski** [comment]
Should be fixed. Try 2.0.1?

Thanks for the report. I'll try and configure Travis so this doesn't happen again.

**Comment by sindresorhus** [comment]
If you have more than one file it's usually easiest to put them in a `lib` folder so you only have to have that one in the `files` array. Then you can add whatever new files without having to care about updating package.json.

**Comment by robwierzbowski** [comment]
Thanks for the suggestion, will do.

**Comment by robwierzbowski** [comment]
Fixed and released.

**Comment by froucher** [comment]
It runs ok, thx!
