### ISSUE TITLE
Stroustrup style if-else

### ISSUE THREAD

**Issue by robwierzbowski** [sindresorhus/gulp-ruby-sass#263]
@sindresorhus I far prefer Stroustrup style for conditional statements. The same line closing and conditional is harder for me to read. Do you mind if I change that style in the xo config for this package?

Thanks for adding XO and updating style, btw.

**Comment by sindresorhus** [comment]
Go ahead. It's your thing.

This is what you want: https://github.com/sindresorhus/xo#rules

**Comment by robwierzbowski** [comment]
Yep, was looking through it yesterday. Thanks.
