### ISSUE TITLE
Logging errors when intermediate / temporary directory contains special regex characters

### ISSUE THREAD

**Issue by fdelacruz** [sindresorhus/gulp-ruby-sass#266]
```javascript
gulp.task('sass', function () {
	return sass('source/')
        .on('error', sass.logError)
        .pipe(gulp.dest('dist'));
});

gulp.task('default', ['build', 'serve', 'sass', 'watch']);

gulp.task('watch', function () {
	gulp.watch('source/**/*.scss', ['sass']);
});
```
So, the first run of my gulp sass crashes. The second time and every other time after that it's ok, but still crashing in between. 
osx: 10.6.8 
node: 0.12.7
npm: 3.3.4
gulp-ruby-sass: ^1.4.0
sass: 3.4.18

![crash](https://cloud.githubusercontent.com/assets/148098/10161793/7fd36d64-6674-11e5-80aa-d80eece42613.jpg)

**Comment by robwierzbowski** [comment]
Thanks for the report. Seems like the intermediate directory path needs to
be escaped. I'll see what I can do.

On Tuesday, September 29, 2015, Francisco De La Cruz <
notifications@github.com> wrote:

> gulp.task('sass', function () {
>     return sass('source/')
>   .on('error', sass.logError)
>     .pipe(gulp.dest('dist'));
> });
>
> gulp.task('default', ['build', 'serve', 'sass', 'watch']);
>
> gulp.task('watch', function () {
>     gulp.watch('source/**/*.scss', ['sass']);
> });
>
> So, the first run of my gulp sass crashes. The second time and every other
> time after that it's ok, but still crashing in between.
> osx: 10.6.8
> node: 0.12.7
> npm: 3.3.4
>
> [image: crash]
> <https://cloud.githubusercontent.com/assets/148098/10161793/7fd36d64-6674-11e5-80aa-d80eece42613.jpg>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sindresorhus/gulp-ruby-sass/issues/266>.
>


-- 
Rob Wierzbowski
@robwierzbowski <http://twitter.com/#!/robwierzbowski>
http://github.com/robwierzbowski
http://robwierzbowski.com

**Comment by robwierzbowski** [comment]
Can you install ^2.0.3 and see if the issue persists?

**Comment by fdelacruz** [comment]
Ok, that seems to fix that issue. It still crashes when run from the watch task, but I guess that's a whole other issue.

**Comment by robwierzbowski** [comment]
What's your watch task? How does it crash?

On Tuesday, September 29, 2015, Francisco De La Cruz <
notifications@github.com> wrote:

> Ok, that seems to fix that issue. It still crashes when run from the watch
> task, but I guess that's a whole other issue.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sindresorhus/gulp-ruby-sass/issues/266#issuecomment-144207478>
> .
>


-- 
Rob Wierzbowski
@robwierzbowski <http://twitter.com/#!/robwierzbowski>
http://github.com/robwierzbowski
http://robwierzbowski.com

**Comment by fdelacruz** [comment]
```
gulp.task('watch', function () {
     gulp.watch('source/**/*.scss', ['sass']);
 });
```
It crashes with the same exact error when I make changes  to my sass file.

**Comment by robwierzbowski** [comment]
Hey @fdelacruz, can you check the version in https://github.com/sindresorhus/gulp-ruby-sass/pull/267 and see if it fixes your issue? I was able to reproduce in an automated test, so it should work.

**Comment by robwierzbowski** [comment]
If it works and the code looks good to you I'll merge and release a new version.

**Comment by fdelacruz** [comment]
Hi @robwierzbowski, how do I add the changes? Manually?

**Comment by fdelacruz** [comment]
It is not crashing anymore which is great, but it is attempting to save the file to a ./.css/style.css which doesn't of course exist.

**Comment by fdelacruz** [comment]
Even the error logging works beautifully..
![error1](https://cloud.githubusercontent.com/assets/148098/10209599/3d84cdd0-67ab-11e5-9cf7-affeb4d1f45d.jpg)

**Comment by robwierzbowski** [comment]
Hmmm, the gulp.dest step is what handles writing... Can you post your sass
task?

On Wednesday, September 30, 2015, Francisco De La Cruz <
notifications@github.com> wrote:

> Even the error logging works beautifully..
> [image: error1]
> <https://cloud.githubusercontent.com/assets/148098/10209599/3d84cdd0-67ab-11e5-9cf7-affeb4d1f45d.jpg>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sindresorhus/gulp-ruby-sass/issues/266#issuecomment-144575547>
> .
>


-- 
Rob Wierzbowski
@robwierzbowski <http://twitter.com/#!/robwierzbowski>
http://github.com/robwierzbowski
http://robwierzbowski.com

**Comment by fdelacruz** [comment]
Sure 
```
gulp.task('sass', function () {
    return sass('source/')
        .on('error', sass.logError)
        .pipe(gulp.dest('dist'));
});
```

**Comment by robwierzbowski** [comment]
Ah, you cannot use a directory source any more. See the new read me. Try a
glob source like source/**/*.scss.

On Wednesday, September 30, 2015, Francisco De La Cruz <
notifications@github.com> wrote:

> Sure
>
> gulp.task('sass', function () {
>     return sass('source/')
>         .on('error', sass.logError)
>         .pipe(gulp.dest('dist'));
> });
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sindresorhus/gulp-ruby-sass/issues/266#issuecomment-144594024>
> .
>


-- 
Rob Wierzbowski
@robwierzbowski <http://twitter.com/#!/robwierzbowski>
http://github.com/robwierzbowski
http://robwierzbowski.com

**Comment by fdelacruz** [comment]
Ok, that fixed the problem.
One small thing, the log keeps saying it is writing to ./style.css which in this at least it's not. It is writing to ./dist/style.css
Shouldn't it say that??
![erro](https://cloud.githubusercontent.com/assets/148098/10217692/77021690-67ff-11e5-98a6-e7336d5b22ed.jpg)

**Comment by robwierzbowski** [comment]
The Sass gem doesn't know the directory `gulp.dest` will write the files to. It is writing these files to a temporary directory, and the gulp plugin removes the temporary directory from the Sass gem output for cleaner logging. So this part is works as designed. 

I may add an error when a user passes a directory as a source. More than one person has missed that change between GRS 1.x and 2.x.

Looks like everything has been addressed. I merged the fix and released as 2.0.4. If there's anything else please reopen or start a new issue, and thanks for working through the bug with me.

**Comment by fdelacruz** [comment]
Awesome, thank you for all the good work, time and effort @robwierzbowski in looking into this.

**Comment by robwierzbowski** [comment]
No problem.

![](http://media3.giphy.com/media/IxJMT1ugyBMdy/giphy.gif)

**Comment by mikehuebner** [comment]
Hate to open this up again, but I'm having trouble with the updated version!
I am still trying to figure out what is wrong but I get this error:
![image](https://cloud.githubusercontent.com/assets/6125123/11283726/eff57ccc-8eba-11e5-91da-7232e4aa7b79.png)

Here is gulp task
```
var files = {
    foundation: [
        './bower_components/font-awesome/scss',
        './src/assets/scss/vendors/animate',
        './src/assets/scss/vendors',
        './src/assets/scss'
    ],
    all: [
        './src/assets/scss/**/*.scss'
    ]
};
return $.rubySass('./src/assets/scss/_main.scss', {
                loadPath: files.foundation,
                style: isProd ? 'compressed' : 'nested',
                sourcemap: !isProd ? true : false,
                bundleExec: true
            })
            .on('error', $.rubySass.logError)
            .pipe($.cached('scss'))
            .pipe($.autoprefixer(prefixes))
            .pipe($.remember('scss'))
            .pipe($.concat('exchange-' + pkg.version + '.css'))
            .pipe($.if(!isProd, $.sourcemaps.write('.')))
            .pipe(gulp.dest('./dist/assets/css/'));
```
If anyone else is having this problem please let me know!

**Comment by mikehuebner** [comment]
Nevermind, figured it out. Got rid of the `_main` and turned it into `main.scss` and that fixed it. Sorry!
