### ISSUE TITLE
Separating gulp tasks into individual files causes slow build

### ISSUE THREAD

**Issue by ionflow** [sindresorhus/gulp-ruby-sass#268]
When running the following gulpfile.js, the sass task completes in under 1 second:
```javascript
'use strict';

var gulp 				= require('gulp');
var sass                = require('gulp-ruby-sass');

var paths = {
    buildCSS: '../build/css/',
}

gulp.task('styles', function () {
    return sass('../src/sass/main.css.sass', {
                compass: true, 
                force: true
        })
        .pipe(gulp.dest( paths.buildCSS ));
});
```

When breaking it into individual files it takes 5 - 6 seconds to complete:

gulpfile.js
```javascript
require('./gulp');
```

gulp/index.js
```javascript
'use strict';

var gulp = require('gulp');
var requireDir = require('require-dir');

requireDir('./tasks', {recurse: true});
```

gulp/tasks/styles.js
```javascript
'use strict';

var gulp = require('gulp');
var sass = require('gulp-ruby-sass');

var config = require('../config');

gulp.task('styles', function () {
    return sass('./src/sass/main.css.sass', { compass: true, force: true})
        .pipe( gulp.dest( config.paths.buildCSS ) );
});
```

gulp/config.js
```javascript
module.exports = {
	paths: {
	    buildCSS: './build/css/',
	}
};
```

**Comment by robwierzbowski** [comment]
I don't see how this could be related to this plugin. The task is the same. Do similar tasks (same time to run, same external config setup) also run slowly?

I'm guessing this is an issue with the amount of files that need to be read of disk, a node issue (or maybe just a reality of the way you're organizing your files).

**Comment by ionflow** [comment]
@robwierzbowski I have not been able to reproduce this with other plugins, which is why I thought it might be related to this plugin.

**Comment by robwierzbowski** [comment]
I don't know how file structure could impact the speed that this plugin runs. What is the difference between times logged to the console?

```
[15:55:36] Finished 'sass' after 1.34 s <- is this different when split?
```

**Comment by robwierzbowski** [comment]
Closing this as won't fix. I am guessing any problem is due to something out of this plugin's control. 

If you find any more information about the slowdown, please post.
