### ISSUE TITLE
Should bang ignore be consider.

### ISSUE THREAD

**Issue by roydukkey** [sindresorhus/gulp-ruby-sass#269]
I would be nice to have suppose for bang ignore locations.

```
sass(['wwwroot/**/*.sass', '!wwwroot/lib/**/*.sass'], config)
    .on('error', sass.logError)
    .pipe(gulp.dest(destination));
```

**Comment by robwierzbowski** [comment]
That's being removed from the glob package (which this relies on) so I
decided not to include here. If glob introduces a way to exclude files I'll
make it available here too.

On Saturday, October 3, 2015, roydukkey <notifications@github.com> wrote:

> I would be nice to have suppose for bang ignore locations.
>
> sass(['wwwroot/**/*.sass', '!wwwroot/lib/**/*.sass'], config)
>     .on('error', sass.logError)
>     .pipe(gulp.dest(destination));
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sindresorhus/gulp-ruby-sass/issues/269>.
>


-- 
Rob Wierzbowski
@robwierzbowski <http://twitter.com/#!/robwierzbowski>
http://github.com/robwierzbowski
http://robwierzbowski.com

**Comment by sindresorhus** [comment]
@robwierzbowski Just use [globby](https://github.com/sindresorhus/globby) instead of `node-glob`. `globby` supports the ignore bang.

**Comment by robwierzbowski** [comment]
I'll take a look at that and at the node-glob/minimatch `exclude` option. 

Leaving this minimatch comment here, I think where I first thought that `!` excludes were going to be deprecated: https://github.com/isaacs/minimatch/issues/65#issuecomment-118652817

**Comment by sindresorhus** [comment]
@robwierzbowski It is. In `globby` we convert `!` to the node-glob `ignore` option, so it's just as performant as `node-glob`.

**Comment by robwierzbowski** [comment]
Awesome! Will do.

On Saturday, October 3, 2015, Sindre Sorhus <notifications@github.com>
wrote:

> @robwierzbowski <https://github.com/robwierzbowski> It is. In globby we
> convert ! to the node-glob ignore option, so it's just as performant as
> node-glob.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sindresorhus/gulp-ruby-sass/issues/269#issuecomment-145254674>
> .
>


-- 
Rob Wierzbowski
@robwierzbowski <http://twitter.com/#!/robwierzbowski>
http://github.com/robwierzbowski
http://robwierzbowski.com

**Comment by robwierzbowski** [comment]
Took a look at this today. It's a little more complicated than it seems because of the way I'm getting the  base paths for the files from each individual source. I'll still try to implement when I get an extra day to work on the plugin.

**Comment by sindresorhus** [comment]
Hey, sorry, this project is now deprecated because Ruby Sass is deprecated.

See: https://github.com/sindresorhus/gulp-ruby-sass#deprecated
