### ISSUE TITLE
The gulp-ruby-sass version 2.0.4 does not compile

### ISSUE THREAD

**Issue by athimannil** [sindresorhus/gulp-ruby-sass#271]
The gulp plugin gulp-ruby-sass doesn't work `"gulp-ruby-sass": "^2.0.4"` for the compiler at the same time it does work with its own old version `"gulp-ruby-sass": "^0.7.1"` 

    var gulp = require('gulp'),
        sass = require('gulp-ruby-sass'),
        notify = require("gulp-notify"),
        bower = require('gulp-bower');
    var config = {
        sassPath: './resources/sass',
        bowerDir: './bower_components'
    };
    
    gulp.task('css', function () {
        return gulp.src(config.sassPath + '/style.scss')
            .pipe(sass({
            loadPath: [
                './resources/sass',
            config.bowerDir + '/bootstrap-sass/assets/stylesheets',
            config.bowerDir + '/font-awesome/scss', ]
        })
        .on("error", notify.onError(function (error) {
            return "Error: " + error.message;
        })))
        .pipe(gulp.dest('./public/css'));
    });

<img width="924" alt="gulp" src="https://cloud.githubusercontent.com/assets/4364227/10462006/463a9436-71ed-11e5-8751-45557010a9e6.png">

**Comment by UltCombo** [comment]
https://github.com/sindresorhus/gulp-ruby-sass#sasssource-options

**Comment by robwierzbowski** [comment]
Please check the readme. The plugin replaces gulp.src.

On Tuesday, October 13, 2015, Fabrício Matté <notifications@github.com>
wrote:

> https://github.com/sindresorhus/gulp-ruby-sass#sasssource-options
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sindresorhus/gulp-ruby-sass/issues/271#issuecomment-147778583>
> .
>


-- 
Rob Wierzbowski
@robwierzbowski <http://twitter.com/#!/robwierzbowski>
http://github.com/robwierzbowski
http://robwierzbowski.com
