### ISSUE TITLE
error when no file found

### ISSUE THREAD

**Issue by TeodorKolev** [sindresorhus/gulp-ruby-sass#273]
`source` does not match any files. Can that be skipped? Basically I want to do: If there is scss file ==> compile it, if not proceed.

**Comment by robwierzbowski** [comment]
No. What is your use case?

On Sunday, October 18, 2015, TeodorKolev <notifications@github.com> wrote:

> source does not match any files. Can that be skipped?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sindresorhus/gulp-ruby-sass/issues/273>.
>


-- 
Rob Wierzbowski
@robwierzbowski <http://twitter.com/#!/robwierzbowski>
http://github.com/robwierzbowski
http://robwierzbowski.com

**Comment by TeodorKolev** [comment]
Case is src has no .scss and gives error

**Comment by robwierzbowski** [comment]
Sorry, I mean what do you want to do further in the task when there are no source files to act on?

`gulp.src` doesn't error when there are no matched source files, so I agree with your suggestion. I added the error because without it we get a weird error from Ruby Sass that talks about watching files. I'll make a PR that logs the no-files message instead of throwing an error, and lets subsequent plugins run.

**Comment by TeodorKolev** [comment]
in other tasks like cssmin it there is not css files it did not throw me error.. Just finish the task. Desired result: if no scss file > finish the task, if add one > run sass

**Comment by robwierzbowski** [comment]
Can you try https://github.com/sindresorhus/gulp-ruby-sass/pull/274 and tell me if that's the behavior you want?

**Comment by TeodorKolev** [comment]
Log and return stream when no files match source, don't error
yes i guess thats it

**Comment by robwierzbowski** [comment]
OK. I'll merge and release a new version.

**Comment by TeodorKolev** [comment]
Thanks for quick resposes and help

**Comment by robwierzbowski** [comment]
No problem.

**Comment by robwierzbowski** [comment]
Published in 2.0.5.

**Comment by TeodorKolev** [comment]
Wow, you have surprise me more and more. Thanks again

**Comment by themefisher** [comment]
Hello @robwierzbowski  , I am still facing this problem .
