### ISSUE TITLE
TypeError: glob pattern string required

### ISSUE THREAD

**Issue by heyalbert** [sindresorhus/gulp-ruby-sass#275]
I don't understand this error. May someone could help? :-)

I installed the newest version of gulp-ruby-sass
and I'm using gulp-plumber

Here is my gulpfile.js:

```
var sass         = require('gulp-ruby-sass');
```

```
var cssTasks = function(filename) {
  return lazypipe()
    .pipe(function() {
      return gulpif(!enabled.failStyleTask, plumber());
    })
    .pipe(function() {
      return gulpif(enabled.maps, sourcemaps.init());
    })
    .pipe(function() {
      return gulpif('*.less', less());
    })
    .pipe(function() {
      return gulpif('*.scss', sass({
        precision: 10,
        style: 'compressed',
        compass: true
      }));
    })
    .pipe(concat, filename)
    .pipe(autoprefixer, {
      browsers: [
        'last 2 versions',
        'ie 8',
        'ie 9',
        'android 2.3',
        'android 4',
        'opera 12'
      ]
    })
    .pipe(minifyCss, {
      advanced: false,
      rebase: false
    })
    .pipe(function() {
      return gulpif(enabled.rev, rev());
    })
    .pipe(function() {
      return gulpif(enabled.maps, sourcemaps.write('.', {
        sourceRoot: 'assets/styles/'
      }));
    })();
};

// ### Styles
// `gulp styles` - Compiles, combines, and optimizes Bower CSS and project CSS.
// By default this task will only log a warning if a precompiler error is
// raised. If the `--production` flag is set: this task will fail outright.
gulp.task('styles', ['wiredep'], function() {
  var merged = merge();
  manifest.forEachDependency('css', function(dep) {
    var cssTasksInstance = cssTasks(dep.name);
    if (!enabled.failStyleTask) {
      cssTasksInstance.on('error', function(err) {
        console.error(err.message);
        this.emit('end');
      });
    }
    merged.add(gulp.src(dep.globs, {base: 'styles'})
      .pipe(cssTasksInstance));
  });
  return merged
    .pipe(writeToManifest('styles'));
});
```

**Comment by robwierzbowski** [comment]
Please read the code examples for gulp Ruby sass. It's a source adapter and
must be set up a little differently than other gulp tasks.

On Thursday, November 5, 2015, heyalbert <notifications@github.com> wrote:

> I don't understand this error. May someone could help? :-)
>
> I installed the newest version of gulp-ruby-sass
> and I'm using gulp-plumber
>
> Here is my gulpfile.js:
>
> var sass         = require('gulp-ruby-sass');
>
> `
>
> .pipe(function() {
> return gulpif('*.scss', sass({
> precision: 10,
> compass: true
> }));
> })
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sindresorhus/gulp-ruby-sass/issues/275>.
>


-- 
Rob Wierzbowski
@robwierzbowski <http://twitter.com/#!/robwierzbowski>
http://github.com/robwierzbowski
http://robwierzbowski.com

**Comment by heyalbert** [comment]
I don't get it. Help, please. :-)

**Comment by whaleen** [comment]
Try gulp-ruby-sass v0.7.1

**Comment by robwierzbowski** [comment]
The readme states "gulp Ruby sass replaces gulp.src". So you can't use any
gulp plugins before it.

On Friday, November 27, 2015, Joshua Vaage <notifications@github.com> wrote:

> Try gulp-ruby-sass v0.7.1
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sindresorhus/gulp-ruby-sass/issues/275#issuecomment-160147084>
> .
>


-- 
Rob Wierzbowski
@robwierzbowski <http://twitter.com/#!/robwierzbowski>
http://github.com/robwierzbowski
http://robwierzbowski.com
