### ISSUE TITLE
Temp directory not compatible with multi-user systems

### ISSUE THREAD

**Issue by lkmorlan** [sindresorhus/gulp-ruby-sass#276]
On a multi-user system, anyone after the first user will get the message "Error: EPERM, operation not permitted '/tmp/gulp-ruby-sass'" due to attempting to use the same temp directory as the first user.

Suggested solution: Give each user their own temp directory, such as "/tmp/gulp-ruby-sass-USERNAME".

This is on a similar topic to #121. I think this issue should be solved so that it does not require any work-around.

**Comment by robwierzbowski** [comment]
Great suggestion. Care to write a pull request?

On Monday, November 16, 2015, Liam Morland <notifications@github.com> wrote:

> On a multi-user system, anyone after the first user will get the message
> "Error: EPERM, operation not permitted '/tmp/gulp-ruby-sass'" due to
> attempting to use the same temp directory as the first user.
>
> Suggested solution: Give each user their own temp directory, such as
> "/tmp/gulp-ruby-sass-USERNAME".
>
> This is on a similar topic to #121
> <https://github.com/sindresorhus/gulp-ruby-sass/issues/121>. I think this
> issue should be solved so that it does not require any work-around.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sindresorhus/gulp-ruby-sass/issues/276>.
>


-- 
Rob Wierzbowski
@robwierzbowski <http://twitter.com/#!/robwierzbowski>
http://github.com/robwierzbowski
http://robwierzbowski.com

**Comment by lkmorlan** [comment]
I think the referenced pull request should do it. I am not able to properly test it at the moment, however.

**Comment by robwierzbowski** [comment]
Fixed by #277
