### ISSUE TITLE
@import does not work

### ISSUE THREAD

**Issue by MrVibe** [sindresorhus/gulp-ruby-sass#278]
@import does not seem to work.
When I try to include a file _global.scss in the same folder as the main file I get this error.

Error: Broken @import declaration of "global"

**Comment by robwierzbowski** [comment]
Sounds like an issue with your sass. Post your code?

On Saturday, November 28, 2015, Vibe <notifications@github.com> wrote:

> @import <https://github.com/import> does not seem to work.
> When I try to include a file _global.scss in the same folder as the main
> file I get this error.
>
> Error: Broken @import <https://github.com/import> declaration of "global"
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sindresorhus/gulp-ruby-sass/issues/278>.
>


-- 
Rob Wierzbowski
@robwierzbowski <http://twitter.com/#!/robwierzbowski>
http://github.com/robwierzbowski
http://robwierzbowski.com

**Comment by MrVibe** [comment]
Yes, you're correct. I upgraded SASS and all is good now.
Closing topic.
