### ISSUE TITLE
gulp-ruby-sass can't compile when the number of scss file reaches 70

### ISSUE THREAD

**Issue by ghjagus** [sindresorhus/gulp-ruby-sass#279]
today, my gulp-ruby-sass not works, and after my debugs  and testing I get the following conclusions:
1. if the scss file number reaches 70, the gulp-ruby-sass will not compile any more. 
2. the scss files whose name starts with "_" are not affect the compiling, and their number can over 70.

---

my env:

gulp -v
[21:29:25] CLI version 3.9.0

compass -v
Compass 1.0.3 (Polaris)

node -v
v5.1.0

**Comment by robwierzbowski** [comment]
Good report. It's probably a limitation in one of our dependencies, either node, gulp, or Sass. I'll look into it.

**Comment by sindresorhus** [comment]
Hey, sorry, this project is now deprecated because Ruby Sass is deprecated.

See: https://github.com/sindresorhus/gulp-ruby-sass#deprecated
