### ISSUE TITLE
invalid option: --sourcemap=none

### ISSUE THREAD

**Issue by mircioku** [sindresorhus/gulp-ruby-sass#280]
Hey there, 

i have a problem and i dont really understand it (new to gulp!) . 

this is my gulpfile.js 

var gulp = require('gulp'),
    sass = require('gulp-ruby-sass'),
    autoprefixer = require('gulp-autoprefixer'),
    minifycss = require('gulp-minify-css'),
    jshint = require('gulp-jshint'),
    uglify = require('gulp-uglify'),
    imagemin = require('gulp-imagemin'),
    rename = require('gulp-rename'),
    concat = require('gulp-concat'),
    notify = require('gulp-notify'),
    cache = require('gulp-cache'),
    livereload = require('gulp-livereload'),
    del = require('del'),
	sourcemaps = require('gulp-sourcemaps'),
	order = require('gulp-order');
	
	

gulp.task('styles', function() {
  return sass('main.scss',{ })
	.pipe(autoprefixer('last 2 version'))
    .pipe(gulp.dest('dist/css'))
	.pipe(rename({suffix: '.min'}))
    .pipe(minifycss())
    .pipe(gulp.dest('dist/assets/css'))
    .pipe(notify({ message: 'Styles task complete' }));
});

when i run gulp styles i get : OptionParser::InvalidOption: invalid option: --sourcemap=none
  Use --trace for backtrace.

I cant get my head around this .. i tried installing also sourcemap and used a format like 

gulp.task('styles', function() {
  return sass('main.scss',{ sourcemap: true})
	.pipe(autoprefixer('last 2 version'))
    .pipe(gulp.dest('dist/css'))
	.pipe(rename({suffix: '.min'}))
    .pipe(minifycss())
    .pipe(gulp.dest('dist/assets/css'))
	.pipe(sourcemaps.write('.',{includeContent:false, sourceRoot:'../view'}))
    .pipe(notify({ message: 'Styles task complete' }));
});

with this i get : OptionParser::InvalidOption: invalid option: --sourcemap=file
  Use --trace for backtrace

anyone can help me , many thanks ;)

**Comment by UltCombo** [comment]
What is your Sass version (check with `sass -v`)? You need at least Sass 3.4. Update with `gem update sass`.
