### ISSUE TITLE
no output file when compiling css file

### ISSUE THREAD

**Issue by littlegreenguy** [sindresorhus/gulp-ruby-sass#281]
Hi, I hope you can help.

I am not receiving any errors, but also am not getting an output css file when I run gulp. I have tried a bunch of different things mentioned in similar issues but am still stuck!

scss:

```
gulp.task('styles', function (){
	return
		sass('sass2/**/*.scss', {
			trace: true,
			verbose: true
		})
		.on('error', sass.logError)
		.pipe(gulp.dest('newcss/'));
});
```

file structure:
gulp file.js
sass2(folder containing basic scss file)
newcss(destination folder)

output:

Nicks-MacBook-Pro:meraki nickalexander$ gulp styles --verbose
[06:14:53] Using gulpfile ~/Google Drive/websites/meraki/gulpfile.js
[06:14:53] Starting 'styles'...
[06:14:53] Finished 'styles' after 59 μs

I'm running OS X 

thanks for any help :)

Nick

**Comment by robwierzbowski** [comment]
That glob isn't correct. Since no files match, the stream ends without any
error. This is how gulp.src works as well.

Can you try sass2/*.scss?

On Saturday, January 2, 2016, littlegreenguy <notifications@github.com>
wrote:

> Hi, I hope you can help
>
> I am not receiving any errors, but also am not getting an output css file
> when I run gulp I have tried a bunch of different things mentioned in
> similar issues but am still stuck!
>
> scss:
>
> gulptask('styles', function (){
> return
> sass('sass2/**/*scss', {
> trace: true,
> verbose: true
> })
> on('error', sasslogError)
> pipe(gulpdest('newcss/'));
> });
>
> file structure:
> gulp filejs
> sass2(folder containing basic scss file)
> newcss(destination folder)
>
> output:
>
> Nicks-MacBook-Pro:meraki nickalexander$ gulp styles --verbose
> [06:14:53] Using gulpfile ~/Google Drive/websites/meraki/gulpfilejs
> [06:14:53] Starting 'styles'
> [06:14:53] Finished 'styles' after 59 μs
>
> I'm running OS X
>
> thanks for any help :)
>
> Nick
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sindresorhus/gulp-ruby-sass/issues/281>.
>


-- 
Rob Wierzbowski
@robwierzbowski <http://twitter.com/#!/robwierzbowski>
http://github.com/robwierzbowski
http://robwierzbowski.com

**Comment by littlegreenguy** [comment]
wow! that was quick! unfortunately I get the same results... I had even tried just specifying the exact file before: sass2/theme_variables.scss

.pipe(gulp.dest('newcss/theme_variables.css'));

But this didn't succeed either

**Comment by robwierzbowski** [comment]
Just to double check, can you try piping your file to a new location using
gulp.src() instead of sass()?

On Saturday, January 2, 2016, littlegreenguy <notifications@github.com>
wrote:

> wow! that was quick! unfortunately I get the same results... I had even
> tried just specifying the exact file before: sass2/theme_variables.scss
>
> .pipe(gulp.dest('newcss/theme_variables.css'));
>
> But this didn't succeed either
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sindresorhus/gulp-ruby-sass/issues/281#issuecomment-168367814>
> .
>


-- 
Rob Wierzbowski
@robwierzbowski <http://twitter.com/#!/robwierzbowski>
http://github.com/robwierzbowski
http://robwierzbowski.com

**Comment by littlegreenguy** [comment]
still nothing I'm afraid:

```
gulp.task('styles', function (){
	return
		// sass('sass2/theme_variables.scss')
		gulp.src('sass2/*.scss', {
			trace: true,
			verbose: true
		})
		.on('error', sass.logError)
		// .pipe(gulp.dest('newcss/'));
		.pipe(gulp.dest('newcss/'));
});
```

**Comment by UltCombo** [comment]
You're not supposed to line-break immediately after a `return`. JavaScript has automated semi-colon insertion (ASI), which means your code is equivalent too:

```js
gulp.task('styles', function (){
    return; // !!
        gulp.src('sass2/*.scss', {
            trace: true,
            verbose: true
        })
        .on('error', sass.logError)
        .pipe(gulp.dest('newcss/'));
});
```

That is, your task returns `undefined` and does not run anything. Try:

```js
gulp.task('styles', function (){
    return gulp.src('sass2/*.scss', {
            trace: true,
            verbose: true
        })
        .on('error', sass.logError)
        .pipe(gulp.dest('newcss/'));
});
```

**Comment by UltCombo** [comment]
If you want to preserve your indentation style, you may make use of the [grouping operator](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Grouping):

```js
gulp.task('styles', function (){
    return (
        gulp.src('sass2/*.scss', {
            trace: true,
            verbose: true
        })
        .on('error', sass.logError)
        .pipe(gulp.dest('newcss/'))
    );
});
```

**Comment by UltCombo** [comment]
Update: I've edited the code samples above to use `sass` (like the original code) instead of `gulp.src`.

**Comment by littlegreenguy** [comment]
spot on! that worked! I knew it was something stupid! thanks very much guys :)

**Comment by UltCombo** [comment]
No problem. :smile:
I've deliberately avoided linking to resources about ASI; it is all too complicated and unnecessary. Most of the time it *just works*™, so fully understanding it is not quite necessary. 90~99% of the time that you have an issue with ASI is specifically this: having a line-break immediately after a `return`, this is basically the only real problem scenario that you should keep in mind. :wink:

**Comment by robwierzbowski** [comment]
Thanks Ultcombo! On my phone, I missed that.

On Saturday, January 2, 2016, Fabrício Matté <notifications@github.com>
wrote:

> No problem. [image: :smile:]
> I've deliberately avoided linking to resources about ASI; it is all too
> complicated and unnecessary. Most of the time it *just works*™, so fully
> understanding it is not quite necessary. 90~99% of the time that you have
> an issue with ASI is specifically this: having a line-break immediately
> after a return, this is basically the only real problem scenario that you
> should keep in mind. [image: :wink:]
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sindresorhus/gulp-ruby-sass/issues/281#issuecomment-168369154>
> .
>


-- 
Rob Wierzbowski
@robwierzbowski <http://twitter.com/#!/robwierzbowski>
http://github.com/robwierzbowski
http://robwierzbowski.com

**Comment by littlegreenguy** [comment]
`having a line-break immediately after a return`
A lesson I'll never forget! Many thanks again :+1:
