### ISSUE TITLE
Wrong path when compiling

### ISSUE THREAD

**Issue by Klemensas** [sindresorhus/gulp-ruby-sass#283]
>var gulp = require('gulp'),
>  sass = require('gulp-ruby-sass');
>
>gulp.task('sass', function () {
>  return sass('./public/css/**/*.scss')
>    .pipe(gulp.dest('./public/css'))
>});

Running this task I get this error:

>[14:22:01] Using gulpfile C:\node\test\gulpfile.js
>[14:22:01] Starting 'sass'...
>[14:22:01] '""C:\Program' is not recognized as an internal or external command,
operable program or batch file.
>[14:22:01] Finished 'sass' after 70 ms

Why would it attempt to use such a path?

**Comment by UltCombo** [comment]
It tries to spawn a Ruby Sass child process: https://github.com/sindresorhus/gulp-ruby-sass/blob/9cb474fd9d3e4e30c49b608eb93c903f7db30d52/index.js#L116-L131

Please check if your Sass gem is installed properly and working.

**Comment by Klemensas** [comment]
Thanks, it turns out ruby has problems when you install it on a directory containing spaces in windows.
