### ISSUE TITLE
This repository workin with .sass extension ?

### ISSUE THREAD

**Issue by jairorudas** [sindresorhus/gulp-ruby-sass#286]
Hi!

This package working with .sass extension??

Thank a lot for your help!

**Comment by robwierzbowski** [comment]
It's just a gulp interface for the Sass gem, so you should be able to configure it just like Sass. Command line options become camelCase options passed to the plugin.

If you don't need Ruby Sass, I recommend trying gulp-sass, that utilizes the libsass library.
