### ISSUE TITLE
Sass does not support tempDir option

### ISSUE THREAD

**Issue by lambrospetrou** [sindresorhus/gulp-ruby-sass#291]
Hello, I am using Ruby gem sass 3.4.13 with this plugin and I get errors with the tempDir option.

You can see in the reference below that the option is invalid for sass, so when you pass it down to the command it fails.
http://sass-lang.com/documentation/file.SASS_REFERENCE.html#options

The solution would be to remove this option before calling the command.

**Comment by robwierzbowski** [comment]
Pull requests accepted. I'm not really supporting this plugin anymore; with most Sass development going towards libsass, I think most people are using gulp-sass now.

**Comment by sindresorhus** [comment]
Hey, sorry, this project is now deprecated because Ruby Sass is deprecated.

See: https://github.com/sindresorhus/gulp-ruby-sass#deprecated
