### ISSUE TITLE
@import does not work 

### ISSUE THREAD

**Issue by rrhussain** [sindresorhus/gulp-ruby-sass#296]
Hi,
I am using gulp-ruby-sass plugin, however when I import my partial into main styles.scss file it does not import.
this is my file setup
'use strict';
var path = require('path'),
    gulp = require('gulp'),
    sass = require('gulp-ruby-sass');

    var pathto = {
        "scss": path.join(__dirname, '/components/scss'),
        "css" : path.join(__dirname, '/components/css')
};
    var glob = {
        "sass": path.join(pathto.scss, '/**/*.{scss,sass}')
}

gulp.task('log', () => {
    console.log(pathto.scss);
    console.log(pathto.css);
    console.log(glob.sass);

});

gulp.task('sass:compile', () => {
    return sass(glob.sass, {
        style: 'expanded',
        lineNumbers: true,
        sourcemap: true
    })
    .pipe(gulp.dest(pathto.css));
});

This is error when I run sass:compile task 

components/scss/_layout.scss (Line 1: File to import not found or unreadable: normalize.

Any help would be appreciate.

Thanks

**Comment by sindresorhus** [comment]
Hey, sorry, this project is now deprecated because Ruby Sass is deprecated.

See: https://github.com/sindresorhus/gulp-ruby-sass#deprecated
