### ISSUE TITLE
SASS compilation breaks on valid media query

### ISSUE THREAD

**Issue by fchristant** [sindresorhus/gulp-ruby-sass#297]
I have a gulp watch task setup that generally works fine, yet it seems to be breaking on this media query:

```
@media not (pointer), (pointer) {
  p { color: currentcolor; }
}
```

For the interested, that code checks whether the browser support the @media (pointer) condition. This is a valid media query in terms of syntax that works fine when you use it directly. Yet it breaks compilation with this error:

_Invalid CSS after @media not ": expected "{", was (pointer),...._

**Comment by sindresorhus** [comment]
Hey, sorry, this project is now deprecated because Ruby Sass is deprecated.

See: https://github.com/sindresorhus/gulp-ruby-sass#deprecated
