### ISSUE TITLE
Outputs to incorrect directory

### ISSUE THREAD

**Issue by faolie** [sindresorhus/gulp-ruby-sass#298]
Using 'latest' in package.json, or just installing from the command line, results, when running, an output to ./.css/filename.css. 

Only when I specified an older version in package.json (as all my other projects were running just fine) did I realise that the new version was writing to this weird directory.

from Terminal:
[09:04:13] directory ./.css
[09:04:14] write ./.css/main.css

Older versions
[09:04:13] directory ./
[09:04:14] write ./main.css

**Comment by sindresorhus** [comment]
Hey, sorry, this project is now deprecated because Ruby Sass is deprecated.

See: https://github.com/sindresorhus/gulp-ruby-sass#deprecated
