### ISSUE TITLE
Disabling  the `debugInfo` and `quiet`  in the config is throwing an error. 

### ISSUE THREAD

**Issue by shirazz** [sindresorhus/gulp-ruby-sass#300]
Disabling  the `debugInfo` and `quiet`  in the config is throwing an error. using the latest version of gulp-ruby-sass and sass v 3.5.5 
**InvalidOption: invalid option: --no-debug-info**
```
{
	debugInfo: false,
    quiet: false
}
```

**Comment by sindresorhus** [comment]
Hey, sorry, this project is now deprecated because Ruby Sass is deprecated.

See: https://github.com/sindresorhus/gulp-ruby-sass#deprecated
