### ISSUE TITLE
`cacheLocation` vs `tempDir`

### ISSUE THREAD

**Issue by bartvanandel** [sindresorhus/gulp-ruby-sass#301]
The readme shows there is a function `clearCache`, with an optional argument `tempDir`. This seems counterintuitive as there is also `cacheLocation`, which then remains untouched. Would you care to clarify the usage here? We found that indeed the `tempDir` sometimes needs to be cleared, but what about the `cacheLocation`? (NB: we're just clearing both now just to be sure)

**Comment by sindresorhus** [comment]
Hey, sorry, this project is now deprecated because Ruby Sass is deprecated.

See: https://github.com/sindresorhus/gulp-ruby-sass#deprecated
