### ISSUE TITLE
OptionParser::InvalidOption: invalid option: -atch

### ISSUE THREAD

**Issue by masumbillah** [sindresorhus/gulp-ruby-sass#303]
OptionParser::InvalidOption: invalid option: -atch
Use --trace for backtrace.

I'm using sass --version
1.13.0 compiled with dart2js 2.0.0

How fix this problem?

**Comment by sindresorhus** [comment]
Hey, sorry, this project is now deprecated because Ruby Sass is deprecated.

See: https://github.com/sindresorhus/gulp-ruby-sass#deprecated
