### ISSUE TITLE
Invalid option --sourcemap-path

### ISSUE THREAD

**Issue by alexmccabe** [sindresorhus/gulp-ruby-sass#72]
Hi, I am having an issue setting the source map path. The plugin creates the source map but doesn't add the map path to the compiled CSS. 

File structure:

```
assets/css
dev/sass
```

gulpfile.js:

```
.pipe(sass({
        lineNumbers: true,
        style: 'expanded',
        sourcemap: true,
        sourcemapPath: 'dev/sass'
    }))
```

Actual error:

```
OptionParser::InvalidOption: invalid option: --sourcemap-path

[gulp-ruby-sass] OptionParser::InvalidOption: invalid option: --sourcemap-path
```

I am new to gulp and sourcemaps, so if I am doing something wrong I apologise.

**Comment by huangjihua** [comment]
[23:09:03] Could not find an option named "sourcemap".
[23:09:03] Usage: dart-sass <input>
[23:09:03] --[no-]stdin    Read the stylesheet from stdin.
-s, --style         Output style.
                    [expanded (default)]

-c, --[no-]color    Whether to emit terminal colors.
    --[no-]trace    Print full Dart stack traces for exceptions.
-h, --help          Print this usage information.
    --version       Print the version of Dart Sass.
[23:09:05] Could not find an option named "sourcemap".
[23:09:05] Usage: dart-sass <input>
[23:09:05] --[no-]stdin    Read the stylesheet from stdin.
-s, --style         Output style.
                    [expanded (default)]

-c, --[no-]color    Whether to emit terminal colors.
    --[no-]trace    Print full Dart stack traces for exceptions.
-h, --help          Print this usage information.
    --version       Print the version of Dart Sass.
