### ISSUE TITLE
Error: spawn ENOENT

### ISSUE THREAD

**Issue by samarpanda** [sindresorhus/gulp-ruby-sass#86]
I am getting error while trying to use `gulp-ruby-sass`. My Gulpfile.js

``` js
  var gulp = require('gulp'),
  sass = require('gulp-ruby-sass');

  gulp.task('default', function(){
    return gulp.src('www/css/scss/app.scss')
      .pipe(sass())
      .pipe(gulp.dest('www/css'));
});
```

Then i run `gulp`. I get this error

``` cmd
sp:sp samar$ gulp
[21:49:46] Using gulpfile ~/Sites/sp/Gulpfile.js
[21:49:46] Starting 'default'...
[21:49:46] Finished 'default' after 10 ms

/Users/samar/Sites/sp/node_modules/gulp-ruby-sass/index.js:101
            var msg = err.trim();
                          ^
TypeError: Object Error: spawn ENOENT has no method 'trim'
    at ChildProcess.<anonymous> (/Users/samar/Sites/sp/node_modules/gulp-ruby-sass/index.js:101:18)
    at ChildProcess.EventEmitter.emit (events.js:95:17)
    at Process.ChildProcess._handle.onexit (child_process.js:787:12)
```

My configuration details:

``` cmd
sp:sp samar$ gem -v
2.2.2

sp:sp samar$ node -v
v0.10.22

sp:sp samar$ sass -v
Sass 3.3.6 (Maptastic Maple)

sp:sp samar$ gulp -v
[21:48:13] CLI version 3.8.6
[21:48:13] Local version 3.8.6

sp:sp samar$ gem list | grep sass
sass (3.3.6, 3.3.5)

sp:sp samar$ ruby -v
ruby 2.1.1p76 (2014-02-24 revision 45161) [x86_64-darwin13.0]

sp:sp samar$ cat www/css/scss/app.scss
$color: green;
body{
    color: $color;

sp:sp samar$ sass www/css/scss/app.scss
body {
  color: green; }
```

Any ideas how can i fix this / where am i going wrong here?

**Comment by NicMcPhee** [comment]
In case it helps some people, I was having this same problem on OS X with both v0.7.1 and v1alpha. Turned out the problem was that I hadn't actually installed sass on this box. `gem install sass` totally fixed the problem.

This is arguably a really obscure error response to the problem, though. Having something say "Hey, sass doesn't seem to be installed – try "gem install sass"." would have saved me a ton of time.

**Comment by robwierzbowski** [comment]
Agreed. This error can also be that the Sass file doesn't exist at the path you've specified, IIRC. We should add a little more information to this error message to help people, cause it seems to happen often.

**Comment by Fastjur** [comment]
For the people from the future, a simple `sudo gem install sass` may fix the issue

**Comment by wswoodruff** [comment]
I think people using npm -- myself included, assume that the dependencies for npm packages will automatically be installed as is normal for npm packages. I had to do `gem install sass` like NicMcPhee and Fastjur mentioned. A check for the folder with `Fs` could be done in Node and a useful error thrown
