### ISSUE TITLE
"Syntax error: File to import not found or unreadable

### ISSUE THREAD

**Issue by yantakus** [sindresorhus/gulp-ruby-sass#88]
I'm issuing the following error with `gulp-ruby-sass`:

```
"Syntax error: File to import not found or unreadable: foundation/components/grid.
Load path: C:/Users/webstyle/AppData/Local/Temp/gulp-ruby-sass on line 13 of ./main.scss
```

Everything worked well with `gulp-sass`.

Here is my configuration:

```
gulp.task('styles', function() {
  return gulp.src('app/styles/main.scss')
    .pipe($.rubySass({sourcemap: true, sourcemapPath: '.'}))
    .pipe(gulp.dest('.tmp/styles'))
    .pipe($.size());
});
```

**Comment by TimorDjd** [comment]
I'm having the same problem.And I can't work out it.The error message is 
"events.js:154
      throw er; // Unhandled 'error' event
      ^
Error: app/styles/ionic-styles.scss
Error: File to import not found or unreadable: bower_components/ionic/scss/ionic
       Parent style sheet: /Users/chinasoft-developer-01/Desktop/demo/app/styles/ionic-styles.scss
        on line 8 of app/styles/ionic-styles.scss
>> @import 'bower_components/ionic/scss/ionic';
   ^

    at options.error (/Users/chinasoft-developer-01/Desktop/demo/node_modules/node-sass/lib/index.js:271:32)"
How can I solve it?I create the project base on the frame of Ionic.The Hyperlinks contain the way that I creat the project. "https://github.com/tmaximini/generator-ionic-gulp".When I run $gulp,it will appear the error above all.I really need you help,thanks first very much!
